= Living on Borrowed Time
:hp-tags: Gastroparesis, Mental Illness, Public Health, Donald Trump

As I write this, my hands are shaking.

I reentered FaceBook society today after taking a mental health break.  In the wake of our questionable President-Elect, I have been forced to reorganize my though processes concerning the next four years of my life.  It is no secret Mr. Trump is no fan of disabled persons and I have no doubt that extends to people of any kind of mental and physical health problems.  You can’t really expect a person who claims pregnant women are an inconvenience to employers to have any sympathy for those of us with chronic and sometimes debilitating illnesses.  It has already been hard to plan with an unpredictable disease like gastroparesis.  Now I am trying to factor in variables like cuts to public health programs, the loss of the Affordable Care Act, and rising prescription drug prices under a regime that has expressed no interest in curbing them.

I saw a post today about a young girl being fitted for leg braces as a result of a disease that will likely take her life in the next 4 years.  The point of the post wasn’t “isn’t my daughter’s life sad” though.  It was “my daughter will need these public health funding programs that Republicans are threatening to cut in the very near future”.  Everyone keeps telling those dependent on such programs to just get out there and vote for a better candidate next election.  As if that were possible.  As if we had the time.  We can’t wait 4 years for a better president.  We need one now.

Many of my friends have commented on what an improvement my health has made recently.  “You got so skinny for a while.”  “We were so worried about you.”  “I’m so glad you’re better now.”  I have a secret to tell you all.  

My health will be short-lived.

You see, almost all of my recent gains have come as a result of a drug called Reglan.  If you don’t shudder at the sight of that name, that’s fine.  It’s marketed as a short-term solution to nausea, vomiting, GERD, and is even sometimes given to pregnant women to help with the production of breast milk.  What Reglan does is stimulate the nerves and muscles of the digestive system in order to help you digest food more efficiently and quickly.  A miracle for someone whose stomach doesn’t digest food at all on its own.  Why don’t we hand this out like candy?  Cure sufferers of chronic stomach ailments once and for all?

Reglan doesn’t start causing problems until you are taking it long term.  “Long term” here means more than a few weeks.  It starts with increased anxiety and nervousness and escalates into full on Parkinson’s-like tremors and muscle movements.  An irreversible neurological disorder call Tardive Dyskinesia.  Symptoms include tremors and shaking in the extremities, facial twitching and grimacing, random movements of the limbs, and difficulty breathing.  Unmistakably linked to use of neuroleptics, antipsychotics, and drugs like Reglan.  In fact, multiple doctors have told me Reglan has an unusually high chance of producing Tardive Dyskinesia over the long term.  

I’ve been on it for over a year.

For starters, I didn’t feel like starving to death at the ripe old age of 22.  But also, there exists a percentage of Reglan users with gastroparesis who never develop complications.  I spoke to someone who’s been on it for 8 years without a problem and I spoke to someone who developed symptoms the day she started taking it.  So you don’t really know.  Maybe you win the lottery or maybe this game of Russian Roulette puts a bullet in you.  

My point in all this is there is a very high probability of me needing to quit my miracle drug in the near future.  If I’m going to develop symptoms, I’m going to do it soon.  I’ve goon too long without side effects.  My doctors are considering taking me off before I develop symptoms to begin with.  For them, the chances of possibly irreversible damage are too high.  I still prefer not to starve to death.  But if you paid attention to my introductory post, you know what happens to me when my stomach isn’t medicated.  If you know me in real life, you got to witness years of it up close.  And my window is closing right as our loving Republican party is threatening to defund and take away the very health programs and insurance policies that will keep me alive.

We don’t have 4 years and we don’t have the option of hoping Mr. Trump’s policies overlook us in the coming reign.  We are going to need help and we are going to need it soon.

And, as I write this, my hands are shaking.
