= It Gets Better
:hp-tags: Mental Illness, Mental Health, Depression

This post is going to offend some people.  This post is going to make some people uncomfortable.  If you experience either of those emotions, this post is for you.

At the same time, this post is going to resonate with some people.  Maybe this post will even help some people.  This post is for you too.

This semester has been a hard one.  It’s been hard mentally and emotionally. One of the things they didn’t tell me when they diagnosed me was that gastroparesis can have a serious effect on your mental health.  They didn’t tell me that my previous minor psychological problems could be multiplied.  They didn’t tell me that an imbalance in my hormonal centers could form.  They don’t tell you all this when they diagnose you with chronic illness because they don’t want it to become a self-fulfilling prophecy.  Unfortunately, that approach leaves those of us who develop those serious mental illnesses completely unprepared.

I had some issues before I got sick.  I was bullied pretty hard when I was young, my family’s emotional support situation was not ideal, and I grew up with a lot of emotional baggage.  Had I made it to adulthood unscathed, maybe all I would have needed is a bit of therapy and a good support system to work through it.  On the other hand, maybe the depression was always in there anyway.  I’ll never know.  I do know that when I got physically sick, I got mentally sick as well.  And I was unprepared.

I’ve spent most of today in bed thinking about the phrase “it gets better” and the campaigns and social movements surrounding it.  Most of these are aimed at depressed and suicidal individuals with the thought process that if only we believe hard enough for long enough, all of our problems will eventually get better.  Through hard work or divine intervention, it will get better.  Here’s the problem with that slogan.

True or not, clinically depressed individuals cannot comprehend that statement.

That campaign stems from a fundamental misunderstanding of what depression actually is.  It works for moody teenagers and temporarily suicidal college students, because, for them, it truly will get better.  Failing a final will not ruin your entire life.  Breaking up with a partner hurts, but the resulting depression is temporary and will heal with the pain.  For a lot of people, it will get better if they wait long enough or try hard enough.

Someone with clinical depression suffers from a break down within the brain.  Certain nerves and glands misfire, certain hormones are not exchanged properly, or certain receptors just don’t work.  There’s a lot of science behind it, and honestly they don’t really understand it completely.  That’s why mental health patients often have to cycle through drugs and dosages before landing on the ones that work for them.  The short of it is depression is a physical failing that creates an uncontrollable mental and emotional imbalance.  And, often, it does not get better.

Take mine for example.  A possibly preexisting imbalance that was triggered or worsened by the onset of a chronic physical illness.  I’ve had two psychologists confirm this is not just the moody blues.  I have developed full-blown clinical depression.  And, not matter how hard I pray or how many drugs I take, it will not go away.  Our current medical approach to depression is incurable.

It will not get better.

Not only will it not get better, people telling me it will actually makes it worse.  It gets better means I didn’t try hard enough.  It gets better puts the fault on me.  It means that today, when I was unable to force myself to get out of bed, I was just being lazy.  I was the one who didn’t try hard enough.  I didn’t have the gumption to feed or dress myself.  I didn’t want to be ok bad enough.  That’s what you tell a clinically depressed person when you say “it gets better”.  That’s not what you meant?  

It doesn’t matter.  

Talking to a depressed person about the future is the greatest exercise in futility I have ever witnessed.  I don’t remember the past days when I was happy and care-free.  I know they existed.  I have pictures.  But I don’t remember those emotions.  Similarly, I can’t see a future in which I am happy again.  I don’t know how to feel that emotion anymore.  I can’t even visualize it right now as I’m writing about it.  My life is zeroed in on today and right now and how I’m feeling and what I’m doing right that moment.

And usually, how I’m feeling is numb.  I have spent the last few months of my life completely at war with my desire to lie in bed and never get up again.  Every morning I wake up and spend about 45 minutes convincing myself it’s worth it.  On days when my stomach is acting up, that time is extended.  And there have been a lot of days of failure.  I’ve missed classes.  I’ve ignored text messages and emails.  I’ve skipped meals.  I’ve spent days basking in the relentless meaninglessness of my own existence, knowing for a fact that nothing I do matters and I will eventually die so why not today.

And your gut reaction will be to tell me this isn’t true.  It’ll get better.  It’s happened already.  Friends telling me they love me and they’re here for me and they’ll talk when I need to.  Here’s the problem.  In those moments, I don’t want to talk to you.  Anything you say to me is meaningless.  Your love is meaningless.  Your love can even be harmful.  I am such a basket of pain and numbness and anxiey that your attempt to intervene can throw me out of a very delicate balance.

Medications calm the chaos.  Medications allow me to get out of bed more days than I normally could.  But they don’t cure that feeling.  They make it all a little fuzzier and distant.  Numb in a good way.  It’s an angry numbness though.  It’s buzzing and itching.  It’s a skin that doesn’t exactly fit.  It’s screaming fuck you at the car behind you that honks their horn for no reason.  It’s sitting up at night crying without knowing why.  It’s letting your body waste away because it’s easier than dealing with the physical illness that will eventually kill you.  It's wondering how long it actually takes to starve to death.  It’s wondering why your significant other loves you enough to watch you go through all this and stick around.  It’s staring at the ceiling wondering how you could possibly tell me I could make my life better.

And it becomes manageable, but it certainly doesn’t get better.
