= A Little Unsteady
:hp-tags: Mental Illness, Mental Health, Depression, Panic Attacks, 

When I first thought of starting a blog, I knew there was a possibility of it being a chronicle of my descent into insanity.  I know that sounds dramatic, but in all honesty there is a very real chance of me not coming out of this illness intact.  Whether it be physically or mentally, I am going to lose something.

I’m thinking about this today because I haven’t been doing well mentally.  My depression has been steadily increasing for the last two weeks, and there’s not much I can do but attempt to ride it out.  I got a brief bit of lift over Thanksgiving with my fiancée, but as soon as she went home I dropped right back into my little pit.  I spent this past weekend staring at a blank word document, forcing myself to do research for a paper, and crying.  And today wasn’t much better.  The paper is due Wednesday at 9AM and instead I find myself compelled to attempt to put something into words I don’t really understand myself.

This morning I woke up for class and I felt shaky.  In my head.

It doesn’t really make sense when I say it like that.  It felt like I was pulling apart at the seams.  I walked around the house making tea, eating breakfast and such, and the whole time I wondered if I was actually shaking.  I wasn’t, but I still drove to school with my arm wrapped around my stomach as if I could hold myself together that way.  I wasn’t any more nauseous than I usually am, and I wasn’t particularly tired.  I just wasn’t all there.  I sat in the car in the parking garage and just tried to breathe and steady myself.  I felt oddly calm otherwise.  There was no anxiety, no signs that I could see anything wrong.  I just couldn’t put myself back together.

Eventually, I had to walk to class.  I checked every so often to make sure I wasn’t actually outwardly shaking.   I hugged my tea to my chest and avoided eye contact as much as possible.  At some point, I realized I was crying again.  I stopped in a bathroom to fix the issue as best as possible.  The alarmed look I received from another student there would have spoken volumes if I could understand what she saw in my appearance.  She cut across the hall to avoid walking near me.  I felt a little more unsteady.

But looking in the mirror before class, I couldn’t see what she saw.  Tears removed, I looked like a completely normal, although tired, college student.  Still, one of my friends in class took one look at me and was immediately concerned.  

“You look like you’ve had the soul sucked out of you.”  

My reflexive smile didn’t reach my eyes.  I could tell he wasn’t reassured.  I mumbled something about being tired and went back to avoiding eye contact.  As I sat in class and went through the motions, I felt like something I was doing betrayed my mental state.  My friend seemed to glance over at me more often than usual, my professor’s gaze seemed concerned, and I felt panic ticking closer every moment I sat there trying to listen to her lecture.  I don’t know if any of this was real.  I imagined my classmates watching me fall apart over and over in that hour of class.  

The drive home is what triggered it.  It takes 15 minutes to drive from Downtown Berkeley to the house I’m staying at.  That 15 minute drive turned into a nightmare of anxiety.  I had become hungry, my hands started shaking, and I began to imagine the jerking motions everyone on Reglan is told to look out for.  The world around me became blurry, the sounds deadened, and I started to sweat in 60 degree weather.  I was having the panic attack I had staved off during class on the road home.

Being the completely logical and sane human being that I am, I kept driving.

I can’t tell you why my brain went to Dory from Finding Nemo in that moment.  Just keep swimming.  It’s happened once before.  I was driving home from a party, before I had gotten sick, and I suddenly realized I was way too drunk to be driving.  I wasn’t swerving, I wasn’t going off the road, and I wasn’t speeding.  A realization just broke over me.  I had no idea how any of that was happening.  I was wasted and terrified and on the freeway halfway home.  And my completely irresponsible response was to just keep going.  Just keep swimming.  The one and only time I drove drunk by the way.

My panic response seems to be just keep going.  Pretend everything is normal until you make it to a safe space.  I’m apparently very good at it.  I fell apart on the drive home today.  I started crying, I got nauseous, I couldn’t breathe, and my mind just abandoned me.  Everything blurred together though I could see the road fine.  I took deep breaths and felt like I was suffocating.  My entire body began shaking but my hands somehow stayed steady.  I started to believe the world was falling apart around me.  I can’t begin to accurately describe it to you.  It felt like I was actually going insane.  I had a total meltdown on the drive home, pulled into a parking spot in front of my house, took a final deep breath, and it was over.  

I’ve spent the rest of today in bed contemplating that moment.  The moment it felt like I was literally losing my mind.  Coming apart at the seams is the only way I can describe it.  If you’ve ever seen someone take a piece of sewing and pull at the two pieces until the stitches holding them together gradually become visible, you know what I’m talking about.  Even the best made pieces come apart with enough pressure.  Sometimes the stitches are loose enough that the thread just pulls apart, and sometimes it just breaks.  But everything pulls apart with enough pressure.

I don’t really know why I feel compelled to share today’s story.  I usually feel like something can be gained from my struggles, but today just feels pointless.  Maybe I could have avoided the panic attack by not going to class.  Maybe it would have just been worse when it finally happened.  Even after some food and a short nap, I’m feeling unsteady.  My brain feels shaky.  My seams feel loose.  I have work to do if I want to graduate though.  I really identify with Dory on days like today.  Find the strength, find the will, and find a way.  Maybe the point is just keep swimming.

I don’t know.
