= Day 5 - Secrets of a Postmates Delivery Driver
:hp-tags: NaNo2017, Day 5, Everyday Life, Audiobiography, Postmates, Work, Depression, Writing,

I’m having a series of those days.  If you have depression, you know those days.  They’re the I didn’t want to get out of bed, I didn’t take a shower, I don’t want to eat, I don’t want to do anything kind of days.  And I don’t want to write.  But in a strange sort of way, that gives me hope for my writing.  I don’t want to write today in the same way that I don’t want to take a shower.  But I love taking showers.  If it wouldn’t be a complete and utter waste of water I’d probably stand in one all day and just be warm and feel the water on my skin and that would be the happiest day of my life.  

But today, and yesterday, and the day before as well, I didn’t want to do that thing.  I didn’t want to experience my very favorite sensation.  Because of depression.  Similarly, when I used to write, I used to feel the most satisfying sensation of fulfillment and joy and power.  It was my favorite activity next to reading, and I’ve lost that over the years.  But I’ve lost it in the same way that today I’ve lost my desire to feel running water on my skin.  

So I begin to wonder if I’ve lost it to my depression.  And if that is in fact the case, can I get it back?  For example, yesterday was the worst of this series of days.  I did nothing yesterday.  I watched Netflix and played iPad games and fiddled with my bullet journal.  But I did still force myself to write a little.  It was a short post, very short of the 1667 goal, and it was private.  But I counted it anyway because it was in the vein of my other writings thus far in NaNo and I didn’t want the day to end with nothing gained.  So despite my depression, I still wrote.  And maybe, if it’s my depression that is taking my writing from me, I can get it back.

So that is my musing on writing and why I might be losing my fire for it recently.

I left this blog off telling the story of Amy, and that story is not finished.  But I can’t tell the rest of it today.  Depression and all that jazz.  And also I don’t really know where to take you next in Amy’s life.  She eventually becomes the young woman writing this and I know how she did, but telling the story to a reader is another task.  Instead, today I want to talk about something I’ve been gathering material and mental notes on for a while.  A few months ago I signed up for and began delivering for Postmates, and there are many things I want to share about the process and the app for others who are interested in the driver’s side of the story.  So here we go:

Firstly, signing up as a Postmates driver is not a thing you can just do in a day.  I mean, you can make the decision in a day, but it will be at least a week before you are able to start taking assignments.  In my case, it took two and a half weeks, but I had extenuating circumstances which I will explain in a moment.  To begin the process, you must visit the Postmates Fleet website in a browser window.  The signup process can be done on a phone, but it has to be done in a browser window and I find that easier on a computer.  The website boasts earnings of $25+ an hour, but I will tell you now I have never made that much in the months I’ve been delivering, even on my best days.

You need a valid email address and a password, and I recommend using one you check often because they email you a lot and some of the emails are important.  Next you need to enter your legal first and last name and a phone number.  Your legal name has to match the one on your driver’s license, which you also need to have, because they use it to run a background check on you.  More on that in a moment.  You also need to use your personal cellphone number, on which you need to be able to download apps (both android and apple are supported) and you also need to be able to receive push notifications and text messages.  There is a drop-down menu of cities Postmates operates in which you can select from, and depending on the city your vehicle type can range from walking to bicycle to other types of motor vehicles.  You can operate in any of the cities Postmates is active in once you are cleared, this initial city should just be the one you think you’ll be in most often.  I selected Orange County and often cross into other cities and areas in my deliveries.  Most cities are only set up for drivers, so if you don’t have some kind of vehicle handy, you may be out of luck.

After going through all the steps to enter your name and driver’s license number and such, you will see a screen which will basically be the progress bar for your activation.  It will ask you to complete some basic questions about yourself, upload a profile picture, and enter your address.  Two important things here.  The picture should be of your whole face and it should be a good view of what you will look like on a day-to-day basis, because it will be shown to your customers and they need to be able to recognize you.  The address also needs to be the one you live at or are able to retrieve mail from, because Postmates will send you a branded reusable bag and a prepaid credit card to use on deliveries.  You cannot begin deliveries without the card they send you, and if you lose it you cannot do more deliveries until you order and receive a new one.

Here’s the part that takes time.  I got my card and bag in the mail about four days after I signed up (there’s no tracking info btw, so you just need to look out for it).  Once you receive the card you need to activate it on the Fleet website, and then they do the background check.  They don’t order the background check until you receive and activate your prepaid card.  Seems a little backward, but that’s how they do it.  The background check takes a few days and you can get a copy of what they receive if you want, no charge.  If all goes well, you’re usually done in about a week and you get to download the Fleet app onto your phone and start accepting deliveries.  Also, yes it is a different app than the Postmates app.  It is called Fleet, and you can have them text you a link to download it from the app store to make sure you get the right one.  And you sign into it using the same login info you used to create your Dashboard account, so remember that email address and password.

It took me longer to get started because the address I gave them didn’t match the one on my Driver’s License, so the background check completed fine, but for some reason there was a hold on my Fleet account.  So when I opened the app it would tell me my account hadn’t been activated yet and I needed to complete all the steps on my Fleet Dashboard in order to become active.  So I had to contact support and open a ticket and wait for them to get back to me.  Here again, the website is full of shit.  Their support site claims they will respond to your support request within 24 hours.  I’ve contacted support twice so far, and both times it took 3-4 days to get a response.  But, once they did respond they were always extremely helpful and got everything sorted.  

So It took about 4 extra days for my account to become active, and it was due to a glitch in their system with my addresses not matching.  So if you’ve recently moved or something like that, you may run into the same problem.  I don’t know if it’s an overall glitch or if it was just me, but they will happily fix it and get your account activated.

At some point in the process, I don’t remember when, you also need to enter your bank account information.  This is so they can pay you.  If you don’t have a checking or savings account or something to that effect, I don’t know how they handle payments.  I don’t think you can use paypal or a visa card or anything.  I specifically remember putting in my routing number and account number and such.  They don’t ask for anything that you can’t get off a check for that account and I did extensive research into it before putting in my info.  So as far as I know, it’s super secure and the only thing they use it for is direct deposits of your earnings.

So here you are, prepaid card activated, background check passed, app downloaded, ready to go online.  I’m going to walk you through the bones of a typical delivery, then go into details about each of the steps, then give my general tips for new drivers.

So this is what happens:  You open the app and press the small green box that says “Go Online”.  It will have already locked onto your location, and will start searching for deliveries in your vicinity.  You can close the app at this point, it will keep searching for deliveries in the background.  Once it matches you with one you will get a notification that a new delivery is available.  Once you open the app and hit Accept, it will show you your pickup location and the order details.  The Fleet app shows you a map, but it doesn’t give you directions.  You have to tap a green square next to the delivery location and it will ask you to choose from whatever maps apps you have on your phone (mine shows Google Maps, Apple Maps, and Waze).  It will automatically enter the destination in the app you choose and off you go.  Once you arrive you need to check the order to make sure you get the correct items, then enter back into the Fleet app and complete the pick up.  Then it will show you the customer’s drop off location.  Go through the same map selection process (you must make this selection every time by the way) and make your way to the customer’s location.  Once you have given the delivery to the customer, you have to go back into the Fleet app and complete the delivery.  Do not do this until you have handed the customer the items.  Once you complete the delivery, the app will revert to the map view and a small notification will pop up telling you what your delivery fee is before tip.  

Now, as it happens, most deliveries are more complicated than this depending on the restaurant or shopping location and and how they are set up with Postmates.  About three quarters of my deliveries are food orders from restaurants, and the remaining quarter is split between other food items (like ice cream or boba drinks) or grocery stores or 7-11s to pick up something else.  You can order almost anything from any store on Postmates, but most people use it for food of some type.  There are some restricted items like alcohol and tobacco products that a Fleet driver is not allowed to pick up.  There is a list in the FAQ of the Fleet app and on the Postmates website.  If you get an order with something like that in it you’re supposed to immediately report the order to support.

Now, the first complication you will run into with delivering is accepting orders.  I often start out at my local Starbucks because I like to pick up a drink to sip on while I’m delivering.  There isn’t enough time between deliveries to pick up food or drinks unless you go offline for a bit to do it, so starting by getting those things or packing a snack or something is a good idea.  So I usually get my drink and hang out in the parking lot until the app matches me with a delivery.  It matches you based on how close you are to the pickup location, and my area is fairly busy, so it doesn’t usually take long to get my first delivery.  If you’re in a less busy area, you might drive toward a more commercial location like a shopping center or some place with a lot of food locations.  It should match you quickly from there.  

From the point that you go online, the Fleet app will be constantly running in the background of your phone, both searching for nearby deliveries and keeping track of your location.  If you are out on a delivery and a new one comes up that you would be close to, it will send you a notification no matter what you’re doing.  If you’re driving, if you’re picking up an order, whatever.  So, if you are not good at handling your phone while driving, I suggest you practice taking short glances at it while driving.  You don’t need to be able to text and drive or anything, and that is illegal anyway, but you need to be able to click the new delivery notification, you need to be able to accept the new delivery, and you need to be able to go back into your maps app if you are currently on a delivery.  Unfortunately, you will probably have to do this while driving a lot.  The new delivery notifications are timed, and if you don’t accept the delivery in time, Fleet assigns it to a new driver.  The timer is about 30 seconds from receipt of the notification.  I like to use a navigation app that still gives directions while you are in another app for this reason.  You have to go into the Fleet app to accept the new delivery, and the Google Maps app continues to give directions while in other apps.

Fleet will only give you two deliveries at one time, for a total of 4 stops.  If you accept a new delivery while already on one, the app will take you through the delivery steps as normal.  For example, you can’t pick up both deliveries and then go to the drop off locations.  You have to pick up one delivery, deliver it, and then pick up the next one and deliver it.  On busy days, I will go from delivery to delivery without a break between.  That is to say, my next delivery will be assigned and accepted usually while I am on the delivery leg of my previous assignment.  So, like I said above, not a lot of time between deliveries unless it’s a slower day.  Even on slow days, there’s only a few minutes after I complete a delivery and a new delivery is assigned.  My area is really busy, it may be different in less populated areas.

The next thing you’ll run into is actually picking up the orders.  There’s a whole list of things that can happen at the pickup location, and the Fleet app will tell you exactly what you need to do once you get there when you accept the delivery.  Some orders are pre-sent to the restaurant and prepaid for, so all you have to do is ask for it by name or order number.  Sometimes you’ll have to pay using your prepaid card, and in those cases you have to take a picture of the receipt and type in the total dollar amount before the app will allow you to complete the order.  Sometimes you will have to order the food once you get to the restaurant, pay with your card, and wait for it to be prepared before you can leave.  If it’s a special thing like groceries or a gas station visit, you’ll have to walk through the store and find the items and pay.  Any of these options can come up at the pickup location.  When you use the prepaid card you have to use it as credit, not debit, and you are not allowed to leave a tip at restaurants that have the option.  It kinda sucks for that restaurant, but you are super not allowed to leave a tip using the prepaid Postmates card.  Also, going back to restricted items.  A driver really really can’t pick up alcohol or tobacco or any other on the list of things.  When you get an order that may contain one of these items, Postmates actually texts you with the list so you don’t forget.

The next fun part is actually delivering the items.  Firstly, the “insulated” bag Postmates sends you is shit at keeping things warm or cold.  I have a Trader Joe’s insulated bag that I use if I think it’s going to be a problem.  What the Postmates bag is good for though is keeping your order from spilling all over the place in your car.  Chick-Fil-A comes to mind in this instance.  Their bags are tall and skinny and they will spill everywhere in your car unless you contain them.  The Postmates bag is good for that.  It is also good for large orders which you can’t carry all yourself.  I always take it into the store with me incase the order is too big.

Actually getting to the customer is also another issue.  Many of mine live in gated communities or apartment complexes or other things like that.  About half of them will leave instructions in the app about getting to them.  Sometimes there is guest parking, sometimes there’s a gate guard to let you in if they didn’t give you the code, sometimes the customer will meet you outside, and sometimes not.  If you can’t figure out how to get to them, there is an option to contact the customer.  Sometimes they’re helpful and sometimes they’re not.  Honestly, this is an issue I don’t have a lot of advice on.  Don’t be afraid to contact the customer if you’re having trouble, but also don’t expect all of them to be helpful.  Sometimes they’re super understanding and sometimes they aren’t.  But like I said, do not press the delivered to customer button until the items are in their hands.  You cannot contact them or support about the delivery once it’s completed.

Your delivery fee is calculated based on how far you had to drive to your pickup location, how long you had to wait there, and then how far you had to drive to drop off.  The minimum fee is $4.  The most I’ve gotten was $11.  And that is pre-tip.  The tip will not show up in your app until 24 hours after the delivery.  It’s their general processing time.  It may take longer depending on the customer’s credit card or bank or whatever.  In my experience, about half of people tip, so don’t be offended if they don’t.  It’s not you.  After five days, Postmates will begin the deposit process into your account.  Depending on your bank, it may take an extra day to show up in your account.  And if the process starts on a weekend, you won’t get your money until the next business day.  So this isn’t a quick way to get money.  If all goes well, from sign up to first deposit, you will receive your first payment in about two weeks.

Other general tips I have:  Have some way to charge your phone while you’re driving.  The Fleet app runs constantly in the background of your phone.  It will drain your battery very insanely quickly.  Something that plugs into your car works best.  Second, have a hands-free setup for your phone in your car.  I have a Popsocket on my phone and a Popsocket clip in my car.  This setup requires the ability to stick something to your phone and a flat surface in your car to stick another thing to, and costs $20.  It works fabulously for me.  There are also numerous other options for car/phone use like cupholder arms, lighter plugs, and other brands of stick on holders.  I don’t recommend the ones that clip onto your AC vents as those can actually damage your car.  But whatever your choice, a hands-free phone holder is absolutely necessary.  Third, having something to do is nice but not required.  Audio book, good music, podcast, whatever.  Something to listen to is good.  Fourth, the Blitz notifications the app sends you are almost always BS.  In my experience, the best times to go out on weekdays are 10am-2pm, and then 4pm-whenever you stop getting notifications for dinner deliveries.  Any time on the weekend is by far the most busy and lucrative though.  Sometimes you’ll get blitz pricing and sometimes you won’t.  Even if you do, it’s not much of a boost.  Fifth, keep track of how much gas is costing you.  If you don’t have a vehicle with good milage, Postmates may not be worth your time.  About a third of my income would go to gas if Skoddie didn’t help me out with it every so often.  Sixth, figure out how you’re going to handle this income when you file for taxes.  If you make more than $600 they give you a tax form and you have to file, but I’ve been told you don’t owe until you make more than $2,000.  I don’t know how it works though.  Fleet does not withhold for taxes though, so do your research, keep track of what you’re making, and don’t forget Postmates earnings when you do your taxes.  Finally, don’t be afraid to use the support options and the customer contact options.  If there is a problem with the order when you pick it up or delivering or anything, there are ways to fix it.  The customer can also contact you, so if you get a phone call or text from a strange number on a delivery it’s probably them.  Don’t be shy, just say you're with Postmates and give them the issue straight.  The last thing is, I've noticed that customers tend to be happier with me if I'm dressed well.  Not like, office dress suit and tie type things, but wearing something clean and nice looking and moderately modest.  I do most of my deliveries in the dresses I purchased for work and they tend to go over well.  Makeup also goes over well, but it's not required.  Just look nice, no ripped jeans or holey shirts.

Overall, I just wanted to write this for people who may use the Postmates app and not realize what the drivers are doing.  I see a lot online blame going to the drivers for things we don’t actually have control over.  For example, I see a lot of people saying they don’t tip because the delivery time is so long.  But if I’m on another delivery when I get your assignment, I can’t actually speed up my current delivery to get to your faster.  Another thing is people getting frustrated when drivers don’t deliver to their door.  I understand this frustration if it’s a house in a quiet neighborhood, but if my customer lives in a closed off apartment complex with no doorman or way for me to get in without being let in, and no one lets me in, I can’t deliver to your door.  I can’t walk through walls.  Also, we have no control over what you see on the Postmates app when you make a delivery.  So any notifications or weirdness with that is not your driver’s doing.  

So I don’t know, that’s it.  It’s generally been a positive experience for me, and most customers are just happy to get their food and move on with their day.  This is just a little insight into my struggles.  So be nice to your delivery drivers.  We’re working hard.
