= Weight
:hp-tags: Gastroparesis, Invisible Illness, Chronic Illness, Body Positivity

So I’ve spent most of the day staring at an Instagram post from two years ago that showed up in my “On This Day” feed on Facebook.  It’s a picture of me the first time I had a mohawk, from my first few days at Cal, and before I had received any treatment for my Gastroparesis.  I know I hadn’t received treatment yet because another post from that feed shows me talking about how hard I struggled to get a visit with a doctor after I had moved up there.

The timeline of my illness around that period is as follows: In May I finally got a referral to and an appointment with a Gastroenterologist.  Also in May, my weight officially hit double digits and my doctor started talking about hospitalization if I continued to lose weight.  Also in May, I was accepted to UC Berkeley.  In June, my Gastro finally ordered the emptying study I had been asking for, and later in the month diagnosed me with Idiopathic Gastroparesis.  In August, I moved to Berkeley, CA to attend university despite the fact that I continued to lose weight.  In September I took many pictures of myself and my firsts at the new school which are now surfacing on Facebook’s “On This Day”.  In October, I weighed in at an even 90 pounds, and a doctor finally put me on medication to control the nausea.  After that point, I was able to eat again, and began slowly regaining the weight I had lost.

Jumping to today, the last time I was in a doctor’s office I weighed in at 185ish pounds.  The result of two years of hard work, medications, therapy, and nausea.  The problem is, I was aiming for 140, and I’ve kinda been giving myself a hard time for over shooting.  I’ve even gone so far as to look up ways to lose weight until I’m back in the range of 140 pounds.  I look at my stomach and thighs in the mirror and hate them, I count my stretch marks and wish they would disappear, I even get frustrated when I try on certain clothes from my “healthier” days and find that they don’t fit me anymore

I’ve done this without realizing how utterly ridiculous that is.

I spent two agonizing years starving and shrinking and dying.  Medications, tests, days lost to side effects and illness and hardships that I wouldn’t wish on my worst enemy.  And here I am whining because I weigh “too much”, not in a medical sense, but in a personal goals sense.

And then those pictures from my first days in Berkeley started coming across my feed again.

I’ve been staring at pictures of my arms without an ounce of fat on them, just enough muscle to function and bones distinctly protruding.  I can see my collar bone so defined it presses against the collars of my shirts and creates hollows in my skin where muscle and fat should be.  There are pictures I never shared from the same time period of myself standing in front of a mirror naked with every bone in my body clearly visible through my skin.  I counted my ribs in one of them today and I remembered feeling them through my clothes every time I scratched or wiped something off my shirt.

I took those pictures so I would never forget that feeling and that time.  And then I forgot.  I got wrapped up in some weird insecurity complex about my stomach not being flat and my thighs not being thin and I completely forgot how hard I fought for that stomach and those things and those stretch marks.  I overshot by 40 pounds.  I'm too healthy for myself, I've regained too much weight.  It sounds stupid when I type it out, but that's essentially what I've been telling myself.

This is my reminder to myself.  Those pictures are my reminder.  My weight is just a number.  My happiness lies in the way my thighs fill out skinny jeans and the way my arms jiggle when they move.  My body has been punished enough.  It continues to be punished every day by a disease that will never go away.

I need to stop adding to it.
