= In Defense of Rage
:hp-tags: Gastroparesis, Depression, Anxiety, Invisible Illness, Anger

I went to my new doctor yesterday.  I was forced to switch after graduating, moving back to my hometown, getting married, and switching to a new insurance company.  This whole thing with my stomach started in 2013 and since then, I’ve switched doctors and specialists at least 15 times.  Over the course of those transfers I’ve been accused of a lot of things.  I’ve had doctors tell me I’m anorexic.  I’ve had doctors accuse me of seeking drugs.  I’ve had doctors call me alcoholic and irresponsible and not worthy of their care.  So I approached this new doctor with trepidation and the thought process that I need to be prepared.  I showed up 20 minutes early with copies of my most recent blood work, gastric empting study, endoscope, and a cheat sheet of all my medications, dosages, and past doctor’s offices and contact information.

And she was the nicest, most sympathetic doctor I’ve ever spoken to.  She admitted she’d never had a patient with idiopathic gastroparesis so young and therefore wanted to hear my whole story from beginning to end.  I told her everything, I showed her my test results and paperwork, and answered her follow-up questions to the best of my ability.  And at some point I must have said or done something light-hearted because she commented on how well-adjusted and accepting of my illness I seem and how impressed she was by it.

In reality, I’m not any of those things and I tend to get really confused when people think I am.  The truth is, I spend most of my days oscillating between rage and apathy so deep I can’t get out of bed.  And the rage is easier for me to deal with.  The rage gives me something to work with.  When I’m mad I can say no fuck this and get myself going until I get too mad and then I shut down into apathy for a while.

I’m going to outline the thought process behind that rage/apathy spiral via an example.  Before I got sick, I was introduced to the magical gift of food that is called pho.  Really, all Vietnamese food, but for the purposes of this rant I’m specifying pho and Thai iced tea, which is some kind of black tea with cream in it and is basically the best drink I’ve ever put in my mouth.  When combined with a nice bowl of pho, it is the meal of gods and I ate it almost every day.  

Now, pho is basically just rice noodles in beef broth, sometimes with different cuts of meat and veggies added.  It is worth saying that I can, and still do, eat it very often.  But once I started getting sick I noticed a correlation with highly caffeinated drinks and my nausea and stopped drinking caffeine.  Once I was diagnosed, I learned it’s actually a specific type of acid in caffeinated drinks like coffee and tea that upsets my already sensitive stomach and causes nausea.  It’s not actually affecting the emptying of my stomach, it’s just irritating my system enough to cause nausea.

Skip to now, somewhere between four and five years after the onset of symptoms and about two years after the diagnosis of my gastroparesis, I decided to experiment with caffeine again.  My thought process was, before, the acid was irritating my already irritated stomach and digestive system.  Now, I’m on all kinds of medication and I wanted to see if I could handle these acidic caffeinated teas.  I started slow with green tea mixed with ginger tea, then plain green tea, and both seemed to go down just fine.  So, in my over confident and eternally optimistic mind, I decided to attempt my very favorite food and tea combo the next time I went for pho.  This happened this week on Tuesday, and then again tonight.

On Tuesday, all went moderately well.  My stomach was a little upset, but it’s honestly been worse and I figured if that was all I had to deal with in order to drink my very favorite drink in the world, I would live.  Tonight, I hardly made it out of the restaurant before I was hit with burning stomach pains and the overwhelming urge to vomit up everything I had just eaten and drank, including my tea.  I ended up taking three different medications, two of which are for emergencies only, in order to keep my food down and make it home.  And somewhere over the course of driving home, I got pissed off.

I used to love food and eating.  Trying different kinds of food was my favorite thing in the world.  I was by no means a foodie, but I would basically try anything once.  I had a friend who would take me to all her random food spots and we’d eat all kinds of random shit together and those were honestly my favorite days.  I used to spend all my money on random food.  I would go over to other people’s houses and eat their random homemade food and love my life.  It was great.  Food is the best part of life.

So imagine my fucking rage when I was diagnosed with an illness that basically limited my food options to the blandest, most easy to digest, most boring meals in the world.  For the rest of my life.  I have been mad for years, and nothing anyone says or does makes me less so.  I realize that being angry at God, the queen, and everyone in between is not going to fix anything but that’s where the apathy comes in.  I get so mad I could jump off a bridge and my only thought on the way down would be “Thank God I don’t have to take another fucking pill for the rest of my life”.  

I literally shut down.  I got so mad the other night, at a matter unrelated to my Thai tea dilemma, that I sat on the couch with a blanket over my head and fumed for hours.  I had to have a blanket over my head because I’ll pretty much get mad enough that seeing or interacting with anything else will set me into an extremely violent and toxic rage spiral.  I try to avoid it.  I’m staving that off right now by writing this post and watching nail polish tutorials.  

I am that level of enraged by the realization that I can probably never drink Thai tea ever again for the rest of my life.  

And a lot of people will surely say this is counter-productive to my mental health and the acceptance process.  In fact, people have already told me this.  There’s a mourning process you go through when diagnosed with an illness like this and anger is just one step in the process.  You eventually have to come to terms and move on and not be constantly mad at life, this is immature, etc.  And maybe I’ll reach that point of acceptance and maturity at some point in my life.  But for now, I stand in defense of my rage.

