= How Are You?
:hp-tags: Anxiety, Depression, Gastroparesis, Chronic Illness, Invisible Illness, Mental Illness, Daily Life, 
 
There are some things about foreign cultures that, when I learn them, make me wonder why the American norm is different.  In this case, when I was learning German in high school, one of the earliest lessons was greetings and how to respond to them and the grammar and sentence structures surrounding that part of German.  Naturally, they have a phrase that basically translates to the english “how are you?” or “how’s it going?” that I remember but can no longer spell.  But, the thing our teacher made very clear was the cultural difference surrounding this phrase.  In Germany, if you ask “How are you?” you get an answer.
 
A real answer.
 
In other words, you don’t ask someone how they are unless you are prepared to have a serious conversation about that person’s day or life since they’ve last seen you.  And in America, at least everywhere I’ve been, the culture is completely different.  You ask “how are you?” and the person is expected to respond with something along the lines “good, how are you?”.  No matter what, the expected response is a polite canned phrase before you continue on with the conversation.  
 
I’m not saying this is how every single conversation like that goes in America.  Among close friends and family, sometimes the question is sincere and the response should actually be about how your life is going.  But for the most part it’s a polite nothing exchange.  And it kind of bothers me because in Germany this greeting signals a sincere desire to connect with your conversation partner whereas in America it's basically a useless filler phrase.
 
I started thinking about this more since I’ve been sick and especially since I’ve been going to church since I’ve come home from college.  When I left for college I weighed 95 pounds and was very sick.  Over the course of two years in Berkeley, I got on medication to help my nausea, gained weight, got on anti-depressants and anti-anxiety medication, and came back generally looking, but not feeling, healthier.  I went to church on Sunday and a lot of the members who know me there were very happy to see me and were talking about how much healthier I looked and all that happy jazz.
 
And a lot of them started the conversation with, “You look so good, how are you?”
 
In my church community, I have a hard time telling who is being sincere and who is being polite, so my gut reaction is to give the canned response to all of them.  “Oh, I’m doing well.  How are you?”
 
And honestly, that response is a lie every time.  If you ask me how I’m doing and I say I’m well, I am lying because I don’t know if you actually want to know how I’m doing because that’s how the culture is in America.  But I’m probably going to continue telling people I’m doing well because I don’t know if they care, I don’t want to make them uncomfortable, I don’t want to make them sad, or some other similar reason because that’s considered polite and correct.
 
So, in case you actually care about how I’m doing, I’m going to tell you right now.
 
“Hey Amy, how are you?”
 
Oh, well some days are better than others, but generally I’ve been feeling pretty unwell.  I’ve gained weight, but I still feel nauseous every day, after almost every meal.  My depression is fighting really hard to take over my life, and some days it wins.  As I’m writing this, my depression is winning.  I didn’t get out of bed until noon today, I only got dressed because I wanted tea, and I only wanted tea because the motions of getting out of bed made me very nauseous and tea generally helps.  And even on my good days I only have the energy for limited social interactions and there is a time limit on my ability to be in public.  A limit I generally only discover by exceeding it.  
 
I’ve been having a lot of trouble figuring out what I want to do with my life now.  I’ve utterly failed at getting a job since December, and I can’t decide if I’m happy or sad about that because I don’t actually know if I can physically sit at a desk all day and work an office job.  But any semblance of me being an independent adult depends on me having an income and livelihood of my own.  Because I'm sick but I'm not sick enough to be on government assistance, having an income means having a job of some sort.  Besides that, the one thing that I spent much of my life wanting to do is work with children in some capacity.  And I can’t do that anymore because I am constantly sick.  So I don’t know what to do with myself and my newly restricted and shortened life.
 
In addition, I’ve been struggling with my anxiety, my germophobia, my growing sense of personal failure, and the fact that I feel like no one actually likes me.  All of these things, I’m told, are side effects of my anxiety disorder and my depression, but I still can’t figure out how to control any of them.  This means that I constantly question my personal relationships, my self worth, and whether or not touching my dog will transfer some germs onto my hands that will make me sick.  I know this all sounds insane, but that is how my brain works now.  And that is how I’ve been feeling lately.
 
How are you?
 
 
