= Happiness
:hp-tags: Gastroparesis, Anxiety, Depression, Everyday Life, Chronic Illness, Mental Illness, Mental Health, 

I looked at my face today.  I looked at it a lot.  I looked at it before I got into the shower, I looked at it as it was rubbing on moisturizer and makeup, I took selfies and checked my makeup in a mirror after eating, and I looked in the car on the way home.  I really really looked at my face today.

I’ve heard all the usual comments about my face from others.  Your eyes are pretty, you look nice today, why don’t you smile more, that’s a good lipstick on you, you should smile more, you have acne, why is your eye red, please smile for me, you don’t look happy, why can’t you just be happy.  

I’ve been thinking about those comments a lot recently.  Yes, I like my eyes, and sometimes I wear weird lipstick colors, but I’ve always kinda considered my face to be a normal enough face.  Nose is a little big, but not funny looking, blue eyes that aren’t particularly pretty, no cheekbones to speak of, mouth on the full side of normal. If I was a Sim, I’d be the Sim you tweak to your desires, not the one you completely re-roll. Not a remarkable face.  But, for some reason, people feel the need to remark on it.

There’s not a gentle way to put it.  Basically, my face doesn’t look happy.  I have Resting Bitch Face.  I don’t smile enough.  When I do smile, it doesn’t seem like I mean it.  I wear makeup that exaggerates this sometimes, subconsciously or not.  I don’t know anymore, but I’ve heard the comments enough to have internalized them and know them as part of my character.

If I think about my face.

But usually, I don’t really think about my face.  I wash it, I put moisturizer on it, and I go about my day.  Today, I thought about it a little more by adding eyeliner, mascara, lip liner, and lipstick over it.  So every time I looked at my face today, I thought about the extra effort I put into it, and I thought about being happy.

Well-meaning people, usually my mother, have taken my happiness into their personal consideration recently.  And most of them have correctly come to the conclusion that I am not happy.  And they have incorrectly used my face as proof that I am not happy.

Rather than my words or actions or any and all knowledge of my life the past few years.

These well-meaning people, and my mother, with often times take to trying to get me to smile for them.  Not in a condescending way or in that gross hey-baby-why-don’t-you-smile-for-me guy hanging out of a truck window way.  Just in a gentle cajoling sort of way.  Sometimes in an attempted trick way.  

Hey!  Smile!

Because an involuntary smile will somehow prove that the unhappiness was all a ruse, that I was just waiting for someone to tell me there was a storm-cloud over my head before I realized I needed an umbrella.  And I’m not singling out my mother because she is not well-meaning, I’m singling her out because she is the most common perpetrator of these shenanigans.  And, arguably, she is the most well-meaning.  She desperately wants me to be happy, so much so that she assaults me in the fruit aisle and demands that I smile.

Because people who smile all the time are happy.

I tried it today.  I molded my face to “look happy”.  I don’t mean by just smiling, I mean I stood in front of a mirror and moved my skin around to try to arrange my face into a happy expression.  What would my face look like if it was just naturally happy?  My cheeks would have to be hollowed to start.  The attractive rounded quality they’ve acquired during my recovery also weighs down the corners of my mouth.  The outer corners of my eyes would have to come up to make me look more awake.  They are also weighed down by skin under my eyes, which seems to have become heavier as the years pass.  I noticed then the dark circles many complain about as well.  Those will have to go.  Tired people aren’t happy. Or is it happy people aren’t tired?  The eyebrows need to “unfurrow” or come apart and the lines between them need to go.  I could probably pluck them into a more attractive shape.  Cover the dark circles with makeup, maybe use a different eye lining technique to make them look wider and more awake.  If all else fails, get some plastic surgery to lift those outer corners.  I would do that while I’m in there getting my cheeks thinned out after losing weight to hollow out my face fails to bring the corners of my lips up.

Did you catch on to the problem yet?

I don’t look unhappy because I am unhappy.  Conversely, I am not unhappy because I look unhappy.  My face is just like that.  I could be the happiest or unhappiest person in the world, but I don’t constantly work my face into a smile so people assume the latter.  And I mean, I’m not going to deny that I am unhappy with my life currently.  But my face doesn’t look like it does because I am unhappy.  My face just formed that way.  I’m not sorry for it.  And I’m probably not going to smile, even if you yell it really loudly.

So that brings me back around to thinking about my face and why people, especially my mom and especially recently, feel the need to comment on the fact that it looks unhappy.  And what happiness has to do with my face anyway.  

Earlier I mentioned my mother desperately wants me to be happy.  She talks about it every time I see her.  And I’ve argued she is the most well-meaning of the bunch, but she is also possibly the most blinded by her own life experiences.  She thinks in order to be happy, you just need to try.  You need to make yourself think happy thoughts, and say happy things, and tell people you are happy.  And this is the key to happiness according to my mother.

But I’m not going to go down the rabbit hole of blaming my parents for my problems or saying they raised me wrong or continue to raise me wrong.  My parents are products of their generation, acted upon heavily by their parents’ raising techniques, but also by their siblings and peers and environments and life experiences.  Just as every generation is a product of those same influences as far back as parents go.  So my mom, having lived a relatively horror-free life thus far, probably can just think happy thoughts and probably can just be happy.  Unless I missed a large chapter of her life-story, she has no reason to have ever encountered clinical depression on a personal level.  So when she says, “Just be more happy” I believe she is honestly giving me the best advice she knows.

The problem is, I almost died a couple years ago.  And I’m not being dramatic when I say that.  I arrived at my gastroparesis diagnosis intimately familiar with every damaged part of my body, starving, counting my ribs daily, and having come to the slow realization that I could actually die before they figured out what was wrong with me.

And honestly, I was going to let it happen if Gastroparesis wasn’t the answer.  I was so tired of the testing and probing and false leads and false hope.  GP was the only light at the end of a very dark tunnel, and, honestly, it’s not a very bright light.  It’s a lifetime supply of nausea, medication, food restrictions, along with the resulting anxiety and depression that comes with attempting to face your own death in your early twenties, and constant whispers in the back of your mind that just not eating is easier than this.

So for me, happiness is still pretty far off.  I couldn’t even begin to describe what it would feel like or mean to me at this point.  That isn’t to say that I don’t feel happy at certain points in time.  I am married to a person I love very much, and she makes me happy.  I have some good friends and I have happy moments with them.  But overall happiness?  Being a happy person?  I don’t know how to be that.  My last therapist told me to set a goal that would make me happy when I accomplished it and I got so stressed out by that assignment I fired her.  I am living an unhappy life under unhappy circumstances and that’s just the way it is for now.

But, in all honesty, the concept of happiness as my parents know it, and maybe even as their peers know it, and as I understand it, isn’t something that I can ever achieve.  My life, my environment, my peers, my spouse, my chronic illnesses, and the state of my country all preclude the American Dream of the white picket fence and the 2.4 kids and a dog.  

I can’t speak for my entire generation, but the life I was promised growing up, the pathway to “happiness”, has slowly become impossible to attain.  And really, that type of happiness was based on the assumptions of previous generations.  They told us it should be our mission to do well in school, go to a good university, get a good degree, and then get a job in that field.  That is how you become happy according to every school counselor I’ve spoken to.  I have done all those things minus the last step, but things have happened in the world and in my life that make the emotion I would feel upon attaining the final step in the process stress rather than happiness.  Even the process of getting the degree stained the whole experience, making having a “good job” in “my field” a source of fear.  I constantly attempt to take that final step, knowing that once I do I will not get the reward I was promised.  I will not achieve “happiness”.

That lack is partially because I have changed and it’s partially because the world has changed.  The job market is more saturated with degrees looking to get the “better” jobs we were promised and there just aren’t enough to go around anymore.  Companies are downsizing or moving to computerized processes, the economy is coming back or failing again depending on the day and who you ask, and the regular desk job employee doesn’t really exist for my generation anymore.  We are at work constantly stressed and tired, too afraid to take a day off but needing one to clear our minds.  My friends who have jobs don’t know how they got them and can offer no real advice on how to get one and who wants a job anyway?  Bosses are terrible and demanding and controlling all at once and your average desk job makes you a cog in a machine that most people my age want to tear down.

But also, almost dying brings you a sort of clarity.  It makes me interact with people differently.  It makes me less likely to just tell myself to smile when my mother wants me to smile.  And really, I don’t unless I’m given something to smile about.  My face is just that way and my life is just that way.  And it makes my mom uncomfortable, because she was raised in a way and environment where talking about sadness and depression was strange and even rude.  Depressed people often got pushed to the perimeters of society with others suffering from mental or emotional illness and you only talked about the good things in life.

I’m not saying that because my mom told me that’s how she was raised, I’m saying that because I’ve witnessed it.  My grandmother did the same thing whenever someone was sad or troubled.  Someone in the family is sick?  No no they’re doing fine, say how about that episode of the Simpsons.  I didn’t know my grandfather was dying until my parents picked me up from school one day and told me we were going to Minnesota for the funeral.  Same with my grandmother.  I didn’t know she had cancer until we were in a hospital room with her and she was telling us about how they had to remove her stomach to get rid of the tumor.  And even then, it still killed her.  But we didn’t talk about it.  So I know where my mom’s fixation on just being happy and only putting happy things out there comes from.

I’ve just become a different person.

I don’t want to be the person lying in a hospital bed blindsiding people by telling them I’m actually dying.  I’m not satisfied just putting on a happy front for people anymore.  Most of the time I’ll tell people I’m doing ok for now, but you never know.  And I don’t see that as being a downer or a sad thing, it’s just the truth of my condition.  I have depression and anxiety and Gastroparesis and those are unhappy things that dominate my life with unhappy modifiers and I can be happy around them, but I’m not always going to be successful and sometimes I’m not even going to try.

I also don’t have happiness as a personal goal anymore anyway.  It’s a vague concept some person made up a long time ago to keep people “on track” and keep the great machine rolling and honestly, I just don’t care anymore.  I don’t think I know anyone who’s truly happy all the time anyway, and I certainly don’t know anyone who claims to have achieved “happiness”.  I know people who like their jobs and I know people who are happily married, but those things aren’t happiness and that’s fine.  

I think what I’m trying to say is that you don’t have to be happy.

I want to live in a world where everything is real instead of happy.  You’re depressed because your spouse is being a jerk?  That’s a valid emotion, talk to me about it.  You’re excited because you got a promotion? Great, tell me about your new job.  But this strange fixation with the fact that so-and-so “isn’t happy” needs to phase out of our culture.  Life isn’t just happy or just sad or just anything.  It’s a mixture of emotions and experiences and they are all valid and deserve their time in the sun.  

If you come to me and tell me to smile because you want me to be happy you’re wasting your time.  I am what I am.  I am usually experiencing something on the unhappy end of the scale, and I’m going to talk about that.  I need to talk about that.  I need people to understand what happened to me, because it’s happening to people like me all over the world and we are being ignored.  So I am unhappy and I am going to talk about it.  At the same time, when something happy comes along, I will also talk about that.  But I will not alter my face into a false construct of what you deem acceptable because you are uncomfortable with my unhappiness.  You need to find a way to deal with the fact that I went through an unimaginably life altering situation, a situation I didn’t expect to survive, and I’m still trying to put myself back together after it.  And that is not a happy process.

That’s just how my face is, that’s just how my life is, and that’s just how I am.
