= Losing My Religion
:hp-tags: Everyday Life, Religion, Gastroapresis, Depression, Anxiety, Invisible Illness, Mental Illness, Mental Health, Chronic Illness

This is a blog post I’ve been putting off making, mostly because it’s not a finished process and I don’t know how it’s going to turn out.  But today happened and I need to talk about it and this is where I come when I need to talk about things now.  So all I ask is that you don’t form an opinion on what I’m about to write until you read the whole thing.

I went to church with my parents this morning.  

Religion has become a complicated topic for me in recent years, but that wasn’t the case for most of my life.  My parents have always been pretty devout Christians.  My dad was raised Catholic, went to Catholic school for most of his schooling years, and, until I told him otherwise, thought Lutherans were Catholic because of a misunderstanding between the words “catholic” and “Catholic”.  My mom was raised Lutheran in rural Minnesota, home of the Lutheranest Lutherans who ever Lutheraned.  That’s not meant as an insult, they’re just REALLY Lutheran in my mom’s home town, and my mom’s parents were no exception.

So me and my brothers were raised all our lives in the Lutheran church, which is a sect of Protestantism for the record.  The “holy catholic church” we pray for every service is the overreaching church of Christ which connects all Christians across the world, not the Catholic church specifically.  The services between Lutherans and Catholics are very similar, but we don’t pray to the saints or the Virgin and a number of other subtle differences.  I could go on about the different flavors of Christian for a long time, the point that you need to take away is that I was raised Christian.

The process of being raised in the Lutheran church is an involved one.  We were woken up promptly at 7 every Sunday to put on our least wrinkled clothes and go listen to our pastor preach and sing some songs and generally learn about Lutheran teachings.  We were all baptized as babies, a practice which not all Protestant sects follow.  At some young age I went through a series of classes about communion, after which I was allowed to begin taking communion.  In middle school I began Confirmation classes every Wednesday night for the duration of the school year which lasted three years.  In these classes we participated in various activities and lessons which were basically supposed to teach us the ins and outs of the Lutheran religion.  At the end of our Confirmation period there were a few weeks in which we as a class had private time with our pastor in which we were allowed to ask any remaining questions we had about religion.

And then, at the ripe old age of thirteen, we stood in front of God and the church and confirmed our faith.

The purpose of this is to confirm what we didn’t have a say over when we were infants.  That is, as an infant my parents baptized me into the church and promised to raise me in the Christian community and place into my hands the holy texts and such.  At the end of Confirmation, we are considered old enough to decide for ourselves whether or not we want to continue in the faith.  It is our formal declaration of faith, confirming the promises that were made for us at baptism.  This is a big deal to me for many reasons, but I’ll get into some of those later.  For now, remember that at the age of thirteen I was asked if I believed in God and the teachings of the Lutheran Church and I said yes.

After we were confirmed, my church had a high school group which met on the same nights as confirmation for middle schoolers, and most nights we spent that time with a youth leader of the church getting further into the details of the teachings and readings and such.  For a lot of my time in this group, which I attended every week, we ended up getting into confused debates with the youth leaders because we were frustrated high schoolers who didn’t necessarily agree with everything we were being taught anymore.  This is one of the reasons I feel that Confirmation is ineffective and happens too early in life.  That we were continuing to question what we were being taught after we had already pledged ourselves to the Church is one of my retrospective red flags.

After high school, the organized classes and meetings dropped off in our church.  I don’t know if other Lutheran churches continue on with college groups.  Ours offers adult bible study classes and informal meetings but, for the most part, the formal involvement drops off after you graduate high school.  In that time, before high school graduation, I participated in several church camps and gatherings and events which were all basically large groups of Lutherans getting together to be excited about being Lutheran and sometimes offered time for introspection and connection to God but were mostly a lot of unnecessary singing and clapping and overly excited guys with guitars trying to make me dance for Jesus.

I say that with more than a little cynicism.  My peers at my church and I were always more toned down about being Christian than those around us seemed to be.  We were fine when we went on camping retreats and such on our own, but thrown into large groups of Lutherans I remember standing out as much less excitable than those around me.  Even in my own church I watched others be swept away by the word of God and was confused about what I was missing.

I explained all this to say that I was very into it all.  I don’t regret the time I spent at Quake or the fundraising car washes or even my season on the church volleyball team.  I loved my God and I loved my church and I may have grumbled when being woken up on Sundays but I got out of bed and I went and I participated and I believed that God loved me and had a plan and life was going to be wonderful as a child of God.

And now I don’t know if I believe anymore.

You see, I went to church with my parents this morning.  It’s become a less frequent event since I don’t live with them anymore, mostly because I have to wake up much earlier to get there on time and sometimes I’m not feeling well enough and sometimes I don’t have the spoons and so I just don’t go.  But today I went and I listened and I questioned and I came home… empty.

I leaned heavily on the promise of everlasting, unconditional love when I was going through school.  I wasn’t the nicest person, I didn’t have a lot of friends, and I didn’t always do the right thing, but at the end of the day I KNEW that there was a God and he loved me and he was looking out for me.  Even on my worst days, someone loved me.  Someone cared.  I needed that growing up.

And then I got sick.

I won’t blame this entirely on my Gastroparesis.  I was asking myself questions I didn’t have answers to before I got sick, but I still had that hard ingrained belief that God was there and it was ok to question because grace and mercy and forgiveness and stuff.  

But I got sick in 2013, and suddenly there were no answers for me.  Suddenly, “God has a plan” didn’t fulfill the holes in me.  I got angry and I got depressed and I got sicker and weaker and for two years I floundered until I got my diagnosis, and there still weren’t answers.  There was a plan.  There was an unimaginable God who apparently loved me but there weren’t answers.  I asked why I got sick and I recieved silence.  I got empty platitudes and vague gestures and uncomfortable looks and all kinds of Bible verses, but there was no one who could tell me why.  

Why, at the age of 20, did I no longer deserve health?  Why did I no longer deserve to live my dreams?  Why did I no longer deserve sanity and joy and assurance?  And why did I suddenly start to feel empty?  And this was only in 2015.  I weighed 90 pounds soaking wet, had a piece of paper saying I was chronically and irreversibly ill, a ticket to UC Berkeley, and no answers.  

I was so angry.  

I was angry for a long time.  I raged at God, I cried and I kicked and I screamed and I fought and I got nothing in return.  I have lost so much in the last four years.  Little pieces of me have died and fell away while I cried and screamed and begged and waited for something.  I don’t know what I waited for.  I wanted some sign.  I wanted something from God, something that could prove that he cared and loved me and that there was a reason.  

I wanted a reason so badly.  I still want a reason.

It was in this climate that I woke up and I went to church with my parents this morning.  Our pastor is wonderful.  Her sermons always make me think.  Today, the message that stood out to me was about loss and faith and the fact that God will always be there, even if you give up on God.  Pastor told a story about a woman who lost her son in an accident with a drunk driver and because of this, she didn’t believe in God anymore.  But it was ok, because God still believed in her.  She was done with God but God wasn’t done with her.  God would never give up on her.

I initially felt heartened by this message.  It seemed so poignant and well timed.  I have been lost the last four years and I had given up on God at some point in that time, but God wasn’t going to give up on me.  But the more I thought about it and the more I turned it over in my mind, the more distressed I got.  

Because I couldn’t believe it.

I wanted to though.  I wanted to believe so badly.  I wanted to take those words into my heart and be comforted and have that same safe feeling I had in high school.  I wanted to know that God was for me and I wanted to be satisfied by that.  But I wasn’t and I’m not.  

It’s not enough anymore.  

This is the part where I get fuzzy and can’t tell you what I believe anymore.  Do I believe there is a higher power which some people refer to as God?  Yes.  Do I think it possible that this being is all knowing and seeing and creator and such?  Yes.  Do I believe it has any feelings of benevolence toward me and my struggles?  

I don’t know.

Because I come back around to an argument I hear a lot and an argument I heard in church today.  If God loves me so much, why has he taken so much from me?  Let’s say you don’t believe God had a personal hand in it even.  If God loves me so much, why has he allowed so much to be taken from me and done nothing to prevent it or comfort me in my loss?  If I stood before the Lutheran all loving God today and only got to say one thing, I would ask him what the fuck he is doing claiming that tile while allowing me and millions like me to suffer and to lose again and again and to do nothing.  I would tell him I don’t want his kind of love.  I don’t want his kind of plan.  I don’t want any part in it.

I won’t deny that I believe in a God, because you can’t be angry at something you don’t believe in.  But I also won’t deny that the most shattering, heart-wrenching, soul-sucking loss in my life has been the unending silence from a being in whose love and grace I believed whole-heartedly for twenty years of my life.

Because I have never felt more alone than in these past years when I have needed that comfort and guidance most.
