= A Letter to my Gastroparesis
:hp-tags: Gastroparesis, Depression, Anxiety, Invisible Illness, Mental Illness, Chronic Illness, Therapy,

I visited a therapist for the first time last week and had a good conversation about my illness and my mental state.  I’ve known for a long time now that grief is part of the process of chronic illness and acceptance of the illness is necessary to continue living a healthy life after diagnosis.  I’ve known this and I’ve fought it because I don’t want to accept gastroparesis into my life and I don’t want to be ok with it.  But that refusal is tearing me apart mentally, so I went to the therapist as the first step towards acceptance.  She thinks she can help me, which makes one of us, and I think I’m at least willing to try.  Her first instruction was to write a letter to my gastroparesis making use of a prompt she gave me to get started in the right direction.  The following is the letter I’ve written, which I will read to my therapist when I see her on Wednesday:

Dear Gastroparesis,

I don’t like you.  I don’t like being forced to second guess every ingredient in a meal before I eat it.  I used to be willing to try anything once.  I used to enjoy walking into a restaurant and ordering the weird thing on the menu I’d never heard of.  And no matter what came out on my plate, I would eat it, and I would usually enjoy it.  I don’t like having to special order meals, I don’t like having to read every ingredient on the box before I buy food at the store, and I especially don’t like the uncertainty you cause when all this fails and I get sick anyway.

I resent you.  I resent having to give up my favorite foods and drinks because of you.  I will never get to order a large iced vanilla latte with extra cream because of you.  I will never taste the flavors of the world because of you.  I resent having to give up my favorite activities because of you.  I resent having to give up on my years of babysitting and childcare dreams because of you.  You exhaust me.  You weaken me.  You make me constantly sick.  I will never dance again because of you and for that, I resent you.  I resent the damage you have done to my body and my mind.  I resent you for forcing me to watch myself shrink until I had no weight left to lose and I resent you for the uphill battle to gain it all back.  And at the end of that battle, you have left me with crippling depression, anxiety, self-doubt, self-consciousness, a weak body image, and no hope of ever being the same and I resent you for all of it. 

I hate you.  I hate when you make me feel sick.  Physically and mentally, you make me feel sick and I hate it.  I hate that you make everything worse.  I caught a cold and you turned it into strep, and then you made the antibiotics impossible to stomach.  I heard about a flu outbreak on campus and you made me believe I had caught it and was going to die from it.  I’ve had colds last for weeks because of what you’ve done to my body.  I hate that you ruined college for me.  I hate that my friends were all out partying while I stayed home and tried to fight you off.  I hate the word idiopathic, and I hate the hopelessness it inspires in me every time I think it.  I hate that it took my doctors years to name you, and even now that I know your name, I have no chance of ever defeating you.

I’m fed up with you.  I’m fed up with your rules.  Every time I think I’ve found something safe you ruin it.  Every meal, there’s something wrong.  Every drink, I have to question it.  Is it too much spice?  Is it too much caffeine?  Too acidic?  Too much fiber?  Oh by the way, I still have to get my daily vitamins, and even those you ruin with your rules.  It’s too much or it’s too little or I’ve forgotten I can’t actually eat that because your rules say no.  All of your rules add up to no and I am fed up.

I’m tired of you.  I’m tired of going to sleep nauseous and waking up nauseous and being nauseous every moment in between and knowing it will be that way for the rest of my life.  You are so well known for the nausea and even vomiting doesn’t make it go away, it makes it worse.  It triggers the pains and the anxiety and the tears.  I’m tired of the abdominal pains, and I’m tired of not knowing what’s causing them or how to fix them.  Every twinge brings new doubts and fears.  What’s wrong with me now?  Oh it’s just you, back again to remind me my body isn’t my own anymore.  I’m tired of the anxiety after every meal.  Will I keep my food down this time?  Will I need to take more pills to keep you at bay?  And the pills, oh the pills.  Every one making me tired or dizzy or causing pain and they’re all because of you and I am tired of them.

You make me sad all the time.  You are relentless and unforgiving and you make everything harder.  I have to plan out every second of my day including how and when I’m going to eat and it makes me sad.  Certain smells set you off, like the dogs at Claire’s house or the cat litter in the garage, and it’s not every time I smell them, it’s just certain times and then I have to leave.  I have to leave my friend’s house before you get too painful to deal with and it makes me sad.  Sometimes I have to not go at all because I know you’re in a mood and it makes me even more sad.  

I feel awful all the time.  Physically and mentally, I feel awful.  I can’t enjoy games anymore because you make me tired and sick after a couple of hours.  I end up hiding in a corner with my phone at parties, counting down the time until everyone will leave or until I can leave and it feels awful.  It feels like I’m letting my friends down.  It feels like I’m letting my wife down.  And at the end of the day, all I can do is lay down and sleep and hope tomorrow will be better.  There is no solution except taking pills that make me feel awful and eating food that tastes awful or not eating at all which carries its own version of awful feelings.  I hate my body and it feels awful.  I hate my mind and it feels awful.  And I hate life and it feels awful.

I am disappointed with what my life has become.  I had plans before you.  I had dreams.  Those plans didn’t include monthly visits to my doctor or a psychiatrist or even a therapist.  I am disappointed because I can’t go do the things I wanted to do.  I can’t go back to school because I can’t physically handle the stress anymore but I also don’t know if I can get a job because that brings its own stress and I am so disappointed.  I can’t be a teacher because my body isn’t strong enough, I can’t be an author because my mind is fogged, and I can’t get my life together because there is so much about you that I don’t know and every time I try to learn I am disappointed.

Most of all, I am afraid.  I am afraid that my health is only getting worse.  I am afraid that I can’t find a way to control my body.  I am afraid of how I feel when I fail to take you into account.  I am afraid of what you mean for my future.  I am afraid of all the questions you bring into my life.  Can I hold a steady job?  Can I still have children?  Can I ever go back to school?  Can I find a way to live with my new reality?  I am afraid of your questions, I am afraid you will say no, and I am afraid of what happens after.  What happens after you say no?  Most of all, I am afraid of what you mean for my future.

I want my life and my body back.  I used to be so very happy in my skin.  I used to feel confident and beautiful and powerful.  I used to love being.  I used to daydream about a beautiful life and a beautiful family.  I want that back.  I want my confidence back.  I want to be able to look at my body in the mirror and smile.  I want balance back in my life.  I want to eat food without fear.  I want control over my weight and my health.  I want to feel joy that isn’t interrupted by worrying about my stomach.  I want to love myself again.  I want to love being again.


