= Things I Can’t Do
:hp-tags: Gastroparesis, Depression, Anxiety, Invisible Illness, Disabilities, 

Denial, Anger, Bargaining, Depression, and Acceptance.  These are what are known as the Five Stages of Grief, or the Five Stages of Dying depending on the situation and who you are talking to.  Basically, people who have lost or are going to lose a loved one are thought to go through these stages of emotion as they process the loss.  According to some psychologists and doctors, these stages are also relevant to people who find out they are dying, or are diagnosed with a life-changing illness or injury.  People who are paralyzed, people who have terminal cancer, people who lose a limb, the list is endless.  Many of these types of people are thought to go through this process of mourning the life they had before their particular disability or illness changed it.  It is thought to be the most healthy and common progression.  A person may not go through all the stages, and may even regress to a previous one after moving forward, but this progression is generally accepted as the norm.

I have been placed squarely in the anger category, though I experience bouts of depression augmented by my actual depression.  My denial phase was mostly spent in search of a cause of my illness.  I was in denial that this was a lifelong affliction, and I was in denial that I would never be able to go back to the way I was before.  I thought, if only I could find the cause, the doctors could fix it, my gastroparesis would go away, and everything would be great again.  I daydreamed about celebrating over double bacon cheeseburgers and root beer floats.  Even when two different specialists in two different cities told me idiopathic meant forever, I fought it.  I requested extra tests.  I spent days researching potential causes and comparing them to my symptoms.  I because very good friends with the librarians at my university.  I may have spent more time researching my disease than I did on work for my degree.  In the end the only knowledge I gained was that my life would never be the same again, and my dreams of living happily ever after had to be shelved with the rest of the fairy tales.  And that’s when I got angry.

Last night I attended the first annual Wastelander’s Ball.  This event is an off-shoot of a larger annual event called Wasteland Weekend.  Wasteland Weekend is a post-apocalyptic themed gathering based mostly around the Mad Max series, though it incorporates themes from other post-apoc stories as well.  It’s similar to a music festival like Coachella, except there are attractions other than music.  They set up a Thunderdome, there is a parade, there is food and bar areas, camping areas, and many apocalyptic themed groups and acts, all assembled in the middle of the desert in California for a few days.  I have known about Wasteland for a few years and have been interested in attending basically since I heard of it, but never knew if I would be able to handle such an event.

So the Ball last night was a good chance to test out my endurance.  The theme was enforced, so you were to attend in your best post-apoc formal wear, many of the people who attend Wasteland Weekend were there, and some of the talent and music acts performed as well.  I spent a few days putting together a costume with the help of friends and attended the Ball with my wife.  I spent the weeks leading up to it thinking it wouldn’t be too strenuous, I would meet some of the people from Wasteland, and see if I wanted to actually attend the festival.  But about halfway through the night, my stomach began to hurt.

One of the symptoms of gastroparesis is abdominal pains and bloating, something I can usually avoid by eating the proper foods and not working too hard.  But there is a special kind of pain I have begun to associate with over-exertion which I haven’t figured out how to avoid and can only be resolved by a full night of sleep.  It’s a sharp burning pain right below my sternum which, if unchecked, radiates throughout my abdomen.  Oddly, it is one of the few pains I experience which is not accompanied by nausea, but the pain can reach a 5 or 6 on the 10 point pain scale if I let it go long enough.

This is the kind of pain that assaulted me last night halfway through the Ball, and, at that point, I began to get angry and depressed.  I associate this pain with the ballet classes I took in college, walking too fast or far while Frisbee golfing, and the rare times I have attempted to really exercise since the onset of my illness.  I don’t associate it with sedately walking around a small restaurant in comfortable shoes and frequently taking breaks to meet and talk to people.  Which is why it made me angry.  I still have a little bit of that petulant child in me, that little voice in the back of my head that says, “but that’s not fair!”  I did everything right yesterday.  I ate simple and small meals like I’m supposed to, I made sure my costume wasn’t restricting or too heavy, I drank plenty of water, and I was still awarded with this burning pain.  The signal that my body was done with whatever I was doing, even if I wasn’t.  

And the rage stems from a few places.  It’s rage against my new restrictions, things my body is deciding without reason or warning.  I avoided creating a costume that cinched in around the middle, a style I find much more attractive than what I ended up wearing, because I knew putting physical pressure on my abdomen would upset my stomach.  I don’t get to wear corsetry anymore.  I avoided solid foods and large meals because I know eating too much would put pressure on my digestive system.  I couldn’t eat the food provided at the venue, I had to eat beforehand, and I had to eat something bland and soupy.  I couldn’t wear heels, my preferred shoe for a formal event, because I wanted my body to be comfortable and secure.  And even with all these precautions, I couldn’t do the one thing I wanted to do at the Ball.

I couldn’t dance.

By the time the music started and everyone was on the dance floor, I was huddled in a corner wishing I could just rip my stomach out and toss it to the birds.  I can’t attend an event like the Wastelander’s Ball and participate in the main attraction.  I probably can’t go to Wasteland Weekend for the same reason.  Even with all my precautions and medications and doctors, I can’t go have fun with everyone else.  I can only sit on the sidelines and watch the party.

And that is what the rest of my life looks like

And that is why I am stuck at Anger.
