= Day 7 - Depression
:hp-tags: NaNo2017, Day 6, Everyday Life, Depression, Writing, Mental Illness, Mental Health

I didn’t write yesterday.

I didn’t write yesterday because I didn’t have it in me.  I almost didn’t write today because I still don’t have it in me.  But I started thinking that’s a slippery slope to me giving up on NaNo altogether, and I promised myself and you that I would give it a fair shot.  And also, if it is my depression that is eating my writing, giving up is giving my depression more power over my life than I want to give it.  And thirdly, if I write today, I have the opportunity to try and explain something you you that I’ve had a hard time explaining in the past.  I write and write about depression because it affects every part of my life, but I’ve never written while in the grip of it.

Because depression makes me not want to write.

I’ve also never explained the difference between being depressed and having depression.  And since we’re in the middle of the Story of Amy, now might be a time to do that.  Because fourteen year old Amy was depressed.  She didn’t not have depression, but she was very depressed.  So today I will attempt to force through the wall of depression and tell you how it actually feels.

At the end of part one of the Story of Amy, I briefly mentioned that Amy wanted everything to be over.  I was dancing around the fact that I was actively suicidal for most of high school.  I was going to go into that feeling in a later post, and it seems that later post is now.  Forgive me for losing the trappings of the storytelling format.  I don’t have it in me.  

When I was fourteen, about the end of freshman year to the beginning of sophomore year, I began to examine my life up to that point and the person I had turned into.  I had some conversations with my closest friends, I thought over some of the things I had done in the past years, I thought about the kind of person I wanted to be, and I found that I was falling very short of my ideal me.  That is to say, I was a heinous bitch and I didn’t know how to fix it, I didn’t think it was fixable, and I decided I was a completely horrible person.

When I was fourteen I became depressed.

There were concrete problems I could think of that I didn’t know how to solve, and I decided it wasn’t worth it.  Here’s the thing, I knew exactly what the problems were.  I had developed habits and a personality that I eventually deemed unacceptable.  I was rude to my peers without cause.  I gossiped and snickered behind people’s backs a lot.  I picked fights with people when I was in a bad mood.  I made impulsive decisions that often lead to bad outcomes.  I was very two faced about it, so my peers saw one side of me that my teachers and other adults didn’t.  And, as a result of all of these behaviors, I didn’t have many close friends, I didn’t have very many positive interactions with my peers, and I wasn’t in a good place socially.  

All very concrete problems.  I identified them at the age of fourteen.  This isn’t even an “in retrospect” list, this is a list I came up with at the time.  What I missed was that I had reasons for acting the way I did.  They weren’t good reasons, and they don’t excuse how I acted, but they existed.  Things had happened in my life that had shaped me into the person I was at that time.  

Nevertheless, I recognized these problems, and as a teenager I had no idea what to do about them.  So my reaction was to become moody and angry with myself, lash out more at people who brought up what I perceived as my failings, put myself down for lashing out, and then eventually became depressed, and eventually became suicidal.  Those emotions occurred because I didn’t have the emotional maturity to recognize my failings and come up with a constructive way to end those behaviors.  Instead of coming up with a set of goals and figuring out what I could actively do to make myself a “better” person, I became so negative and angry with myself that I got worse.

That is what I mean by becoming depressed.  It wasn’t a hormonal thing or any kind of imbalance, it was literally a set of personal behaviors and emotional immaturity that lead me to believe I didn’t deserve to live anymore.  I’ve talked about this before on this blog when I wrote about the “it gets better” campaign.  There is a kind of depressed that will eventually get better.  There are problems that will clear up, there are situations that will go away.  This was one of those things.  Those behaviours I had seen in myself and those reactions I had to past life events were the emotional reactions of a young, hurting, damaged teenager.  And I’m very happy I had a support system back then that recognized I was going through something, and kept me from doing anything to harm myself.

Because I got better.  

I eventually figured out what I needed to do to break my toxic habits, I eventually matured and became a better person, and I eventually reach a place of peace with myself.  I won’t claim to be the best human in the world, but I had stopped many of the behaviors that I found so reprehensible at the young and terrible age of fourteen.  My problems then were concrete and solvable, and solutions came.  And I became not depressed at a certain point.

Being depressed is different from having depression.

When I was fourteen I was depressed.  Now, after gastroparesis, and anxiety, and Fetzig, and college I have depression.  The difference now is I don’t have a set of recognizable problems that I can list out that are completely solvable.  When you have depression a malaize of sadness and lack of energy and motivation follows your life and comes and goes as it desires and is sometimes affected by your life but most of the time is not.  

Some argue that my current depression is simply caused by all the drama caused by gastroparesis, and once I deal with those emotions it will go away.  I don’t really buy that explanation for two reasons.  First, I have experienced the kind of depression that has a resolution.  All those years in high school when I was steeped in self-loathing and suicidal thoughts and anger, there was always a light at the end of the tunnel.  There may have been days I didn’t see it, but it was always there.  Second, my gastroparesis isn’t a solvable problem.  It’s not a curable disease.  So at some point I may come to terms with that and accept my new normal emotionally, but my physical situation will not change.  I will still become nauseous for no reason, and I will always have the current emotional imbalance than I believe causes my depression.

When I woke up this morning, I wasn’t depressed.  I was tired.  I woke up tired.  So I turned my alarm off, rolled over, and went back to sleep for a few more hours.  And even after a few more hours of sleep, I was tired.  I woke up the second time tired, nauseous, and depressed.  My psychiatrist likes to argue that the morning lethargy is a cause of my medications, many of which have drowsiness as a side-effect, but I don’t feel like that explains it all.  There’s a difference between waking up yawning and getting out of bed, and completely ignoring any reason to get out of bed and going back to sleep.  If I had a regular job, I would have been hours late today.  I didn’t make the decision to go back to sleep, I just did it.  In fact, I am very concerned about my psychiatry appointment tomorrow morning, because I’m afraid I’m going to do the same thing and miss it.

Derailments aside, there is nothing going on in my life that is making me more tired.  There is no reason for me to need three extra hours of sleep, and then a further two hours in bed resting.  Not even playing on my phone or watching TV, just laying there relaxing.  That is having depression.  When I was depressed, I never felt the lethargy and lack of motivation I feel today.  I never sat down at my computer and stared at a blank Word document with nothing to write.  Being depressed is being sad but still being fiery and angry and wanting to change.  Having depression means feeling nothing.  

I am not sad today.  I am not too sad to write or too sad to work or too sad to get out of bed.  I have nothing in me.  I didn’t even get out of bed this morning until I remembered I had promised my parents I would come over for dinner and I was too unmotivated to go through the social dances required to cancel on them.  When I tell you I don’t have it in me to write something entertaining or informative or anything like that, I mean I literally don’t have it in me.  I didn’t write yesterday because I lacked emotion to the point of apathy.  Had I a job yesterday, I would have spent it staring at my computer screen in whatever office I worked in.

I don’t know if that distinction makes more sense.  But there is a very big and definable difference.  I was depressed when I was in high school.  I have depression now.  Without a light at the end of the tunnel.
