= What Makes Life Worth Living?
:hp-tags: Everyday Life, Anxiety, Depression, Gastroparesis, Suicide, Invisible Illness, Chronic Illness, Mental Illness, 

So Skoddie and I have been having a conversation over the last few weeks or months about me and my depression and what I’m doing with life and other related subjects.  Part of the issue of discussion is the question, “what do I do now?”  And this question has been plaguing me since I graduated college because, up to that point, my purpose in life and my big life altering goal had been to get my degree.

Which is a big deal.  

I spent pretty much 25 years of my life building up to obtaining a degree from the best university I could afford, in a subject I enjoyed and was passionate about.  And, despite the setbacks, obstacles, and depression, I got it.  I have a little piece of paper in an envelope next to my desk that represents all of the work I’ve completed since I started kindergarten at 4 years old.

And while that’s an achievement I am extremely proud of, It isn’t a goal I really set for myself.  I mean, no one told me to set my sights on UC Berkeley, no one told me literature was the subject to choose, but not going to college was never really an option.  The question I was asked when I was growing up wasn’t, “Will you go to college after high school?” it was, “Where will you go?”  It was assumed that I would go to college and get a degree, so I did.  It was a strange mix of self-set goals and societal expectations, and I’m done with it now.

So, now what?

Part of the problem is that along the way I gained severe mental and physical illnesses.  And part of the problem of depression is that it makes me want to lay in bed and do nothing until I die.  And part of the problem of gastroparesis is that I can’t do much, including a lot of things I really enjoy, so laying in bed until I die seems like a really attractive option.  It’s a combination that makes it hard to set goals and get things done.  

I spent about six months applying and interviewing for jobs that require English degrees for a lot of reasons.  Chronic Illnesses are expensive so I need an income, almost everyone in my life told me that’s what I was supposed to do after college, and I didn’t really know what else to do.  So Skoddie helped me create a nice resume, I contacted people who would act as references, and I threw myself out there.  But over the course of those months, for whatever reason, I started to more and more hate the idea of getting a conventional office job.  I started to doubt my ability to obtain such a job, I started to doubt my physical ability to work such a job, and I started to ask myself why I was trying to get one anyway.

Because I’ve never wanted a conventional office desk job.

I temped a lot in offices during my city college time and I hated it.  I hated everything about it.  I can’t even say why.  It might have been the type of work that temps tend to be assigned, it might have been the lack of sincerity I sensed in the interpersonal interactions of the people working in the offices, it might have been the lack of free thought and the staleness of the “creativity” involved.  I don’t honestly know if temping just gave me a skewed image of offices, I just know I don’t want to work in one if I can avoid it.

So Skoddie and I started talking about alternatives to the office jobs I had been applying for, and, naturally, we landed on writing.  Because I love writing and if there’s one thing I am confident about and one thing I know I can do, it’s write.  I used to do stupid shit when I was bored in high school like pick an essay topic that I knew was BS and see if I could convince the teacher that I was actually right. I had to stop senior year because my English teacher caught me at it and made me re-write an essay I had done because “this is well written but you and I both know you don’t believe it”.  I think more of my teachers knew I was full of shit along the years, but he’s the only one who said anything.  And then I got into college and found out scholars get paid to do that kind of stuff and realized I was just practicing for my college career without knowing it.

The problem with writing though, is that my life has changed drastically since I used to write vampire horror stories and Harry Potter fanfiction in high school.  My outlook on life has changed, my opinions on a lot of social issues have changed, my understanding of myself, my sexuality, my body, and my mind has changed.  And If I’m going to write for a living, I want to write about that.  Not just those topics, I want to write something that means something to me.  That isn’t to say my one-shot horror stories didn’t mean anything, but they don’t say what I want to say anymore.  So If I’m going to write for a living, I need to figure out what I want to say, and how to say it.

Another part of the discussion with Skoddie about living with my depression and finding what I’m doing with my life has centered around figuring out what about life excites me.  I tend to think more of what am I passionate about.  Why am I living?  What am I living for?  Illness makes these questions hard to answer.  Because depression limits the things that I care about, and gastroparesis further limits the things I’m able to care about and do.  

So what am I passionate about?

It’s hard to identify passion sitting at a desk writing a blog post.  I love reading and writing.  I love dancing and bike riding and frisbee golf.  I love knitting and crocheting.  I love makeup and nail polish and baking and tea.  I love animals, especially dogs.  I love children.  I love this blog.  But am I passionate about those things?  Can I make a living doing them or turn that love into something I can live with doing?  

Some of those things, I have to cross off the list because of gastroparesis.  I can dance on a good day, but those are few and far between now.  I can’t ride a bike or golf until it cools down because I overheat easily now.  I can’t be around children or animals much due to various anxieties and illnesses.  I don’t have the money, energy, or skill to professionally do makeup or nails.  Some of those are solvable issues and some of them aren’t, but for the immediate future my list is shortened.  And it would take passion or excitement to overcome the drag of depression and get those issues resolved.

That brings us back to writing and what I want to say with my writing.  Because I do love this blog and I do love reading and writing.  I know I am passionate about writing because I sit here and do it in my free time, despite the depression nagging at me to get back into bed.  But this blog contains all the writing I’ve done since I graduated minus some cover letters and posts I decided to keep private.

These are the things I care about most, these things I share with you in my private part of the internet.

I care about women’s rights and LGBT+ rights and healthcare and safe spaces for PoC.  I care about visibility for invisible illnesses.  I care about food health and nutrition and affordable access to food and food information.  I care about mental health care and support for mental health patients.  I care that so many of my friends and family don’t know about these things and how they affect so many millions of people.  I care about these things so deeply.  It hurts my heart when I have to explain what depression is like to another person, but at the same time I am overjoyed that they asked and possibly will listen to the answer.

These are the things I care about and want to write about.

Now how do I do it?
