= For Pounce
:hp-tags: In Memorial,

Hello my kitten, my baby, my beauty, my friend.
 
I saw you yesterday tired and failing.  I saw you yesterday and held you in my hands.  There have been many times, my beauty, my friend, that I thought you would leave me, but I saw you yesterday and knew that this… this is the end.
 
I remember when you came to me, tiny and fierce.  You came to me and I carried you with all the tenderness in my 5-year-old heart.  You wouldn’t be a good pet, they told me.  You were feral and strong.  You wouldn’t make a good pet, yet I carried you home.  Do you remember, my beauty, my friend, hiding behind the boxes in the garage?  You earned your name that first night,  attacking everything that walked by your lair.   Do you remember meeting the dog and do you remember teaching him who was the boss of the yard?  But also, you remember, curling up next to him when the nights got cold?  Tiny and fierce and feral and strong, my beauty, my friend, you made it your home.  
 
That summer was the first year the rats never came.  We didn’t find their droppings behind the toolbox and we never saw their little tails whisk out of sight.  We didn’t hear the scratches in the rafters on cool summer nights.  We heard you though, my beauty, my friend.  We heard you prowling the shelves and the stacks.  We saw your eyes glowing out of the darkness, heard you growl and hiss and bite.  That was the year the rats never came until we found them under the deck in the yard.  Trophies one and all of your hard work, your fierceness, your joy.  Ours was the only house on the street that never had rats again.
 
I remember, my beauty, the first time you went to the vet.  They told me you would come home tired and you would never have babies and my 5-year-old heart thought that was unfair.  We didn’t ask you if you were a mother, after all.  But the first day you came home, angry and tired, you escaped to the yard.  I remember, my friend, finding your bird trophies along the walk that first day and I realized you were fine.  A mother you weren’t, my beauty, my friend, but even with stitches across your belly you were feral and strong.  And I loved you that day with all my 5-year-old heart, my beauty, my friend, tiny and fierce, feral and strong.
 
I remember you, beauty, growing old with me.  Stalking across the yard in search of your next prey.  Rolling in the dirt, exposing your belly to the sun.  Letting the young children pat your head on their way to school.  I remember you waited for them every morning, even in the summer when no school was open.
 
I knew you were growing older and slower when I found you in the shed.  You had been missing for days and I thought the worst.  Your neck was a mass of infected sores, you were shivering and scared.  But you came when I called you, tender and tired.  The vet told me you wouldn’t survive the attack, but my 5-year-old heart knew better.  You were a fighter, my beauty, my friend, and and I found your bandages in a pile on my bed. You were back in the yard a month later, better than before.  
 
I remember from then on, my beauty, my friend, after that first attack, you became tender and strong.  I was confused that first day you waited for me after school.  You waited I don’t know how long, and came running to my car, prize in your mouth and pride in your lines.  I was proud of you then, in all my aged 5-year-old heart.  What cat can survive a coyote attack, yet there you were with a lizard for a gift.  I loved you that day and everyday after.  You came to my car with presents and pride and received the only reward I could give, my love and affection.  It was Spring time then, my beauty, my friend, and you brightened my days to no end.
 
The second time I found you under the house they told me it was the end.  You were 15 then, and tired. The surgery you needed was hard.  And they were right, you were never the same, but still you came home, battered and old.  And your hunting days were behind you, and the house was your home.  And the rats never came back, though you had retired then.  And I loved you all I could, with my 5-year-old heart.  Battered and tired were we, my beauty, my friend, but you carried on.
 
And I remember the day I had to leave you.  I thought on that day that it was the end.  You were 18 and tired, going blind and moving slow.  I would be gone for two years, and I thought my beauty would leave me then.  But still you persisted, growing more tired and grumpy each year.  I feared for you each day while I was gone, and returned to you still joyful, independent, and strong.  You didn’t remember me then, but I remembered you.  You were my baby, my kitten, my beauty, and my friend.  Feral and strong, 20 years old.
 
And now here we are, my beauty, my friend.  And this time, this time it was the end.  I was not there when your journey came to its end, when you closed your eyes, when your spirit wended. I held you yesterday, your body so frail, and wept for our lives and the paths we now tread.  I love you my kitten, my baby, my beauty, my friend.  My 5-year-old heart is yours to the end.
