= In Which I Offend all of my Well-Wishers
:hp-tags: Gastroparesis, Body Positivity,

There’s this weird succession that occurs when you become sick and start losing weight.

First, there’s a lag while news spreads that you are ill.  During this time, well-meaning people begin congratulating you on your weight loss, thinking it was intentional and desired.  They believe, like so many others in society, that you were not happy with your body originally and that now you are fixing it.  So they congratulate you.  This phase lasted for about two months of my illness.  That was about the first 40 pounds of weight loss.  While I starved, friends and family came to me smiling and hugged me and said I looked great and good job on the weight loss.  The problem is, during this time period in the illness, I didn’t know how to tell them they were wrong.  I had no diagnosis, I had no answers, and I had multiple doctors accusing me of anorexia.  So I smiled and thanked them for the compliment and let the news spread naturally.

Second, there’s the collective realization and mourning of your illness, followed by the commentary about how skinny you’ve become and the questions about how you’re going to manage your illness.  This phase of my illness lasted about a year and a half, when my weight dipped into double digits and those who saw me on a regular basis realized it wasn’t intentional and something was wrong.  During this period, I still didn’t have a diagnosis, I didn’t have a reliable way to stop the nausea or the weight loss, and I didn’t have a way to express to those around me that I really wished they would stop telling me how worried about me they were.  I can guarantee, I was way more worried than anyone else involved in the project, and the constant reminder that everyone in my life was basically watching me die wasn’t in anyway helpful.

Third, if you are lucky, there’s the collective relief of a diagnosis and regaining the weight.  This phase is characterized by everyone in your life coming to tell you how happy they are that you’re getting better, how much healthier you look, and oh by the way have you tried X insane diet because my brother’s friend’s wife thinks it’s really good for you and you should try it.  This is the final phase and is currently ongoing.  This phase is characterized by long conversations with everyone who has been paying attention during the last two phases, educating them on the illness that is killing you, listening to their unsolicited medical advice with a smile on your face, and walking away feeling like shit about your body.

Here’s the thing about me and my body image.  I never had a problem with my body or my weight or anything like that until I got sick.  A lot of adolescent girls go through a period of body hate and insecurity where they get really uncomfortable with their bodies and how they look.  We are socialized from a young age to believe we are too fat, too thin, too pimply, too pale, too dark, and any number of other “too much” things.  Everything is wrong with our bodies and the fashion and beauty industries offer us many expensive and time consuming solutions to these “too much” problems.

But I never believed them.

I wasn’t ever a paragon of self-confidence, but I was always at least comfortable in my skin.  My issues were always internal.  I was more worried about whether or not people perceived me as a bitch than whether or not they thought I was fat.  I’m not placing myself above those girls who go through those problems at all though.  I just never understood the fascination with makeup and beauty products and never used them.  I was working on my personality instead.  So imagine my surprise when my entirely dependable and beautiful body revolted, transformed, and turned into an enemy.  My stomach no longer works.  I can count my ribs.  I literally almost starved to death before we finally figured out what was wrong with me.  

I’m reading a book right now about the science of sex and arousal and the female body and I reached a part where the author relays a story about a recent mother who breaks down crying because she now has to figure out a way to love her body again after birth.  Her friends assure her she is beautiful, but she tells the author those reassurances made her feel worse about feeling bad about her body to begin with.  So maybe people who have given birth can relate to how I feel now that all my friends come running up to tell me how good I look now.  Maybe those who have suffered from eating disorders can understand.  Maybe other chronic illness sufferers can understand.

But if you’ve never suffered, there is no way for me to explain the deep and utter loathing I experience towards my body at this point in my life.  And part of that loathing came from the scrutiny I faced while my body was going through this transformation I never wanted.  It came from everyone telling me I looked lovely or healthy or too skinny or sick while my body internally revolted and decided to self-destruct without my permission.  I came from the juxtaposition of my hatred of my illness and society’s praises of my losses.  

Like the pregnant woman in the book I’m reading, all I want is for everyone to stop reassuring me I look fine, and start telling me it’s ok to be angry at my body for changing.

Society hammers us with messages that our bodies are not pretty enough and not smooth enough and them when we finally believe them, society says, “No, you’re fine, why would you think that?”  Our body hatred stems from society’s reactions to transformations and changes which are sometimes out of our control.  At the height of my weight loss, when I weighed 90 pounds, I would sit in my room counting my ribs and cry for hours.  And then I would leave my bubble of self hatred to be told I looked so skinny and good.  Or someone would ask if I was ok because I looked so ill.  And I would return to my bubble and count my ribs and play those comments over and over in my head, and I finally came to the realization that my body is wrong or was wrong and I’ve never been enough and that’s why everyone waited until I got sick to comment on it.

I don’t have a solution to this problem, other than to ask people to stop commenting on each others’ weights and body changes.  But will that help?  Will that cure my self-hatred?  Will that make our little girls feel better about their acne?  Will it make our pregnant mothers ok with the changing landscape of their bodies?  I don’t think that’s all there is to it.  But, it’s sure a start.
