= Denial
:hp-tags: Gastroparesis, Depression, Anxiety, Invisible Illness, Chronic Illness, Mental Illness, Mental Health,

There are two blog posts that I’ve been trying to write and I had originally split them because I thought they were completely separate problems.  But really one informs the other.  So, if while you’re reading this you feel like I lost the plot, stay with me.  

On Monday I made dinner three times.  

When eating alone, my dinner routine is generally the same.  I take my pre-meal pill, wait the allotted 30 minutes for it to take effect, and go downstairs to warm up my dinner.  I’ve been shopping a lot at Trader Joe’s because they have a lot of premade, frozen meals that I can just quickly heat up that pretty much stay within my dietary guidelines.  I usually shop on Monday for the entire week.  So when I went to the store Monday afternoon, I found out that a couple of my favorite items had been rotated out for new things that either didn’t fit into my guidelines or didn’t look interesting.  So I went looking around the store for replacements and landed on their chicken enchiladas and a bag of chicken fried rice.

Now, the thing to mention about the items I usually eat is most of the time they are meat free.  Something like chicken fettuccine would be turned into mushroom fettuccine instead, so you still get a meaty quality without the meat.  Another thing to mention is that most of the time, the items I buy are precooked and all I am doing is warming them up later.  

Neither of these were the case with the chicken containing items I purchased on Monday, though I didn’t notice my mistake until I went down Monday night to make dinner.  Because they weren’t precooked, both items had a minimum temperature to heat the meal to in order for it to be safe to consume.  So when I took out the enchiladas, I thought, “Well that’s unfortunate, but whatever, I’ll do my best.”  

I popped the container into the microwave for the specified time, stuck the food thermometer into the center to gauge the temp, and discovered it wasn’t cooked all the way through.  Ok, back to the microwave, cook for a little more time, check again, it still isn’t cooked all the way through.  But you see, when I’m saying it isn’t cooked all the way through, I don’t actually know that.  All I know is that it isn’t reaching the specified safe temperature for consumption.  I go through the cycle a few more times, get extremely frustrated, and end up throwing away the enchiladas because I can’t get them to the point where I am convinced they are safe to eat.

And then I did the same this with the chicken fried rice.  I had this thought in my head that the enchiladas were only such a problem because they were thick and full of filling and, after I calmed down, would need to be heated in the oven if I tried them in the future.  Surely the fried rice would be easier to heat to the correct temperature quickly in the microwave.  But it was not to be.  Even after heating the rice and chicken three times as long as specified, the chicken stayed twenty degrees too cold.  

So I got frustrated and threw that away too and sat on the floor and cried.  

At this point in the post, I hear my therapist’s voice asking me why I would cry over something like that, so let me explain.  TV dinners, microwave dinners, instant snacks and pretty much anything you cook has a “safe” temperature printed on the box that you need to check your food for before eating it.  Before gastroparesis, I ignored that temperature warning and just ate whatever without checking.  Because I never got sick from a TV dinner, I never thought it was an important warning.  That is because, before gastroparesis, I had never had food poisoning.  

Since June of 2013, when my gastroparesis symptoms started, I have had food poisoning-like symptoms four times from various meals.  One of those was a TV dinner I believe I improperly heated before eating.  

Anyone who’s had food poisoning knows it isn’t a fun ordeal, but usually once the offending toxins clear your system you’re fine.  With my gastroparesis, even while take my nausea controlling medications, food poisoning means spending at least two days attached to the toilet and a further week or so being very gentle with my stomach.  It’s debilitating, and I do everything I can to avoid it.

Cut to Monday, when suddenly I couldn’t safely eat two meals I had really been looking forward to trying.  Two meals that I probably would have eaten without a thought before gastroparesis.  But on Monday the only thing going through my head was the anxiety surrounding unsafe food, the paralyzing fear that I would make myself sick from eating undercooked chicken, and the frustration with myself for those anxieties.  Part of it was the anxiety itself and part of it was that I was so mad at myself for being a crazy person about food temperature.  That’s why I sat down and cried in the middle of the kitchen floor instead of doing something productive.

I’ve told you this story so that I can make a point about myself and my life.

A lot of my friends and family talk about the day I will get better.  They talk about the day I will get a job, and the day I will have a family, and the day I will have a normal life.  They talk about how happy they are that I am healthy now, and when I bring up that I am not they deny it.  They talk about how God will heal me, they talk about yoga, they talk about connecting with my body, they talk about having a positive relationship with my illness, and they don’t see the truth.

Even some of you reading this don’t see the truth.  

I don’t blame you.  You don’t see it because you aren’t living it.  You don’t see the day-to-day of my life.  You don’t see the little struggles I go through.  You don’t see me taking the pills and you don’t feel their side-effects.  Monday was not a fluke.  My anxiety rules my life.  My depression rules my life.  My gastroparesis rules my life.  The anxiety and the depression may someday come under control, may someday even go away entirely.  I don’t believe that possibility at this point in time, but that’s what my mental health doctors tell me.  

My gastroparesis will not go away.  Ever.

Again, I hear my therapist’s voice in my head saying I don’t know if that’s true and that stranger things have happened.  The thing is, my therapist is a new age, God-fearing, crunchy mom, hippy.  She believes in miracles and she doesn’t know a lot about gastroparesis.  My parents, also extremely religious, echo in my head, telling me that God will take my gastroparesis away someday and all I have to do is pray for it.  Members of my gastroparesis support group on Facebook echo in my head saying the same thing.  All we have to do is pray.  These people have said these things to me.  I’m not just imagining it.  My friends have said similar things.  It’s not, “If you get better…” it’s, “When you get better…”

It is denial and denial is dangerous.

It is dangerous to believe that I will one day magically get better.  It’s dangerous because it leads to forgetting that I’m sick on the positive side and getting frustrated that I’m not getting better on the negative side.  Denial means not dealing with the matter at hand.  Denial means pretending everything is ok and ignoring the signs that it isn’t.  

I can’t be in denial anymore.  I don’t get that luxury.  I have to deal with the fact that I will be sick for the rest of my life.  I have to deal with it emotionally because if I don't I have no chance of dealing with my anxiety or my depression.  The more I ignore and deny my gastroparesis, the more days I will spend sitting on the floor crying.

And the more you ignore and deny it, the less I want to have you in my life.
