= Day 3 - The Story of Amy Part 2
:hp-tags: NaNo2017, Day 3, Everyday Life, Bullying, Sexual Assault, Audiobiography, Pre-GP

Today is a day that makes me question myself and my purpose.  Today is a day I do not want to write.  Not only because the things I am going to write about are hard for me to remember, but also because there are other things I want to do.  I want to watch YouTube and Netflix and curl in bed with my bullet journal and contemplate improvements to my life.  Or better perhaps, log onto Postmates and run some deliveries.  Make some money.

But I started a story yesterday and I didn’t tell all of it, and I think there are some important things that I left out that deserve to be told.  If I were telling that story with the intention of telling you about me, there is more to the story the editor would want.  And I admit to fatigue at the end of yesterday’s post, so I didn’t finish Amy’s story with the gusto that I started it and I don’t know if I can do that today.  But I accepted this challenge and I started telling this story, so I should tell all of it.

And maybe I’ll even forgive myself at the end.

We will begin where little blonde Amy with the curly pigtails died.  Not at the age of ten, when the fragile thing in her heart broke and unleashed the pain she had been hiding for years.  Not even the first time she fought back; tears streaming down her face, fists clenched white with rage, voice cracking with emotion and exertion and sobs.  She fought back.  But even after those things, I believe Amy could have been saved.  She was hurt and broken, but broken things can be mended, and she had a soul sister who would have helped had she known to ask.  I do believe that.

Parts of this story will remain shrouded in the veils of the past.  I can only half tell it, and in doing so I do a disservice to Amy’s memory.  She deserves the whole truth told, and I have often wondered why I don’t tell it.  But for today; nothing happens in a vacuum, and Amy’s life was no different.  She was besieged at school by those who knew nothing of her.  She was besieged after school, when she attended a daycare center full of children who knew her strangeness.  She was besieged at home, though her parents did their best to mitigate the damage there.  Her brothers had reached the age where it was no longer cool or good to be friends with their sister and so they poked at her where her parents couldn’t see.  And little broken Amy at the age of eleven entered middle school.

It was in this environment that a man entered her life.  

I will call him a man and refuse to refer to him otherwise, though he was only sixteen at the time.  He was old enough, and he knew what he did was wrong.  And he was a man in Amy’s eyes anyway, five years her senior.  I don’t remember when he started, but he started slowly and slyly.  This is how I know he knew he was wrong.  He waited until she was alone, or until his movements would go unnoticed, and he began to show her attention.  He began to smile at her, he began to stare at her, he began to touch her.  Not anywhere inappropriate of course, for that would be noticed.  But he began slowly and he escalated slowly.

And this is how Amy died.

Bit by bit, moment by moment.  One day, he brushed past her as she sat alone.  Innocent enough, until she thought about what had touched her in the brush.  But it was an accident.  Boys will be boys after all.  It wasn’t his fault he was firm in her proximity.  She said nothing then.  Next, she began to feel his eyes follow her as she moved.  Staring as she entered a room, staring while she chose a book, staring while she did her homework, staring staring staring.  Surely she was imagining it, but every time she looked up he had to look away.  And she said nothing then.  Next, a touch at the back of her neck as she bent over a table, but when she turned he was in conversation and no one had seen anything.  Next, another brush, knocking her books to the floor as she worked.  Next, the softest caress down the back of her neck, and gone again when she turned to look.

She said something then while the child in her quaked.  I don’t like him, she said.  He makes me uncomfortable.  But her voice was swallowed in the noise of the moment and by the words harmless and imagination and sensitive.

He became bolder then.  One day he plucked a book from her hands and held it to his chest.  He wanted to see what she was reading, but his eyes weren’t on the cover and she had lost her page.  One day he grabbed her curly wild hair and twitched it in her face.  It looked so nice, he wanted a feel.  He laughed when she pulled out of his reach.  One day he laid his hand on her waist.  The briefest contact, a silky apology.  She was in his way, he needed to pass.  There was plenty of room.  One day a message appeared on her computer screen while she played a game with her friends.  He wanted to play too.  I can see you online.  She had never given him her screen name.

She turned twelve in this time, and her female body began its changes.  

And she spoke again, alone and afraid, and again she was swallowed by sensitive and imagination and emotional and there was nothing wrong and everything wrong and she shrank and shrank until she thought he’d never see her again and even then even then it continued.  She dreaded his face and his hands and his name and his laughter.  Every time he was there she waited for his hands and his voice sliding over her like a sludge she couldn’t wash off and her cries fell on deaf ears unless they wanted to torment her some more.  She stopped playing games on the internet so he couldn’t see her presence, she stopped working alone, she stopped everything and even then he found ways.  He became bolder and touched her arm but when she cried out they shushed her and looked away and when she left they berated her back.

Even then even then she could have been saved she just needed someone to look but instead they lashed out and she was emotional and young and she lashed back and they looked away always away and he was a man and dangerous and a child and innocent and he came closer and no one saw for months upon months of touching and smiling and whispers and caresses no one looked when she cried no one looked when she ran and she burned with rage and fear and spite and he came closer and closer and then and then he griped her leg and smiled with all his teeth and even then they saw and did not see and then she hid and cried and then and then and then…

And then he found her alone and then his iron arm swept around her and she screamed and screamed and no one came and he whispered and shushed and tried to calm her and she screamed and he dragged through her clothing like paper and still he smiled with all his teeth and she kicked and bit and screamed a scream of rage and pain and sorrow and fear and finally her bars were opened and she ran crying all the way and would have kept running had there been road enough to run.  And when she collapsed and confessed all there was to confess there was a fire and a storm and a howling of fury and it swept around her and torn at her skin and little Amy cried in the eye of it and welcomed its rage and fed its fury and told it all there was to tell and it burned hotter at the telling and wilder at her tears.  And when the storm passed he was gone gone forever and even then even then Amy could have been saved.  Even then she was tired and broken and hurt but her hands reached out and she could have been saved.

But.

I don’t believe you.

Cuts deeper than the sharpest knife.

And that was the day Amy died.
