= On My Current Body Image
:hp-tags: Gastroparesis, Depression, Anxiety, Invisible Illness, Mental Illness, Eating Disorders, Body Positivity, Suicide, Chronic Illness, 

This is probably going to get into touchy territory for some people, but it’s something I need to get out.  So read my tags and if you can’t handle those topics, feel free not to read.

I’ve been at war with my body for the better part of the last two years.  I mean mentally, physically, in all sense of the phrase, I am at war.  I hate my body.  I hate everything about it.  I hate everything it is doing.  I hate everything I have to deal with because of it.  And I hate myself for hating my body because I used to love it so much.

The day I got sick I weighed 165 pounds.  It was my fourth semester of taking ballet classes and my second semester of Pilates at my college and the women who taught the classes made every second worth it, which meant I was in great shape.  I don’t mean six-pack having, weight–lifting shape.  I mean I felt great.  I felt comfortable in my body.  I wasn’t model thin but I felt like I looked good.  I was happy.  Everything was in balance.

The day I got sick my body betrayed me.  As far as anyone can tell me, my stomach just up and quit its job.  It took two years of testing and poking and prodding to prove to me that there was nothing wrong with me other than my stomach just didn’t work anymore.  No one I’ve seen has any clue why.  It was a slow transformation in my mind, but I went from loving everything about the body I was in, to hating every inch of it.

I started out by trying to placate my new condition.  I’ve been following the diet as far as I could find on forums and support groups online.  I cut almost all of my favorite foods out of my diet, I spent a lot of time trying to decide which vitamin supplements would help and which would harm, I stuck to a fairly strict rice-based diet.  Easy to digest, soft foods, liquids frequently.  I tried everything.

But even though I knew exactly what was wrong with me and what I was supposed to do to help make it better, almost nothing worked.  I’m on one of the most dangerous drugs on the market to help stimulate the muscles of my digestive system, I’m on the blandest diet possible, I eat smaller meals less frequently, and I’m still nauseous.

I am nauseous all the time.

And at some point, I decided I was fucking done with it.  My body, which I had loved and cared for as much as possible, continued to betray me.  I continued to lose weight, I sunk further into depression, I went mildly insane, my hands shook, my vision fogged, I developed migraines and headaches, and I deteriorated and deteriorated.  I hated it.  My body has betrayed me.

And so I went to war.

I’ve gone back and forth in my mind on whether or not I have an eating disorder or if I’m just suicidal.  The short of it is that it’s easier to just not eat.  I don’t usually wake up nauseous, it’s just when I add food, so some days I don’t.  Because then my body can’t let me down.  My stomach can’t fail me if I don’t put anything in it.  And it’s not fear of the nausea, it’s rage.  It’s anger and resentment that I have to deal with this bullshit everyday without relief.  I don’t get a break.  There are some days I only eat due to Skoddie’s prodding.  Some days I eat because I feel bad about what I’m doing to myself.  Some days I just don’t eat.  But at the same time, I’m not going to starve to death.  I'm actually gaining weight somehow.  So am I developing an eating disorder or am I suicidal?

Or am I just angry?

My therapist thinks I’m grieving.  She thinks I can move past the anger and her first instruction was to write a letter to my gastroparesis explaining what I hate/resent about it.  But I don’t know if I can separate the two.  Do I write to my gastroparesis or do I write to my stomach directly?  Do I ask it why it just decided to stop working one day without warning or reason?  Do I ask it if I did something to trigger this?  It’s an argument I’ve been having in my mind since I was diagnosed.  It’s an anger I’ve had since I heard the word “idiopathic” attached to my illness.

I’m not sure if this post makes sense in the way I wanted it to.  But this is what I mean when I say I hate my body.  I hate what it’s doing to me.  I hate what it’s turned into.  It’s not about weight, or shape, or color.  It’s about the betrayal I feel deep inside when I think about what I could have been if I didn’t wake up nauseous that day in 2013.
