= Grief
:hp-tags: Gastroparesis, Depression, Anxiety, Invisible Illness, Mental Illness, Mental Health, Chronic Illness,

I don’t know where I first heard or read this notion, whether it was a book or a movie, but it was some external media in which a character had just died and the protagonist was contemplating their death.  They said, “It felt like the world should have stopped, but it kept going.  [Character Name] was gone, and the world should have stopped to notice.  But it seemed that no one did.  The sun kept rising, the grass kept growing, and people kept living their lives around me.  But it should have stopped.”

I’ve often felt that way about this little journey that I’m on.  I think about that long remembered quote often.  The world should have stopped.  Something tragic has happened.  Why does the world keep turning?

I’ve long since realized that it’s really only a tragedy to me.  Other people are going to be affected by my illness like a stream is affected by a rock.  It’s a minor inconvenience to go around, but the water will keep flowing.  And truthfully, my world didn’t even fully stop.  It couldn’t.  I was in the middle of college at the time.  If I had stopped to take in the tragedy, I wouldn’t have started again.  Like a stream what meets a wall of rock or a winding canyon.  It puddles and tries to get around and is generally distressed, but after a while it bores itself a channel and it might not keep going with the same speed or vigor, but it does keep going.  That was my life when my gastroparesis started and again later, when I got diagnosed.  I never stopped, I just bored a channel and tried to keep on my path.

I think I should have stopped.

I’ve often related life to a river or a stream.  It has an origin, a path, branches, twists and turns, obstacles, but eventually it gets to the end.  All rivers end at the ocean.  Just because they haven’t gotten there yet doesn’t matter.  Water is tenacious, it has a way of winding and breaking its way through any barrier.

Humans aren’t like water though.  We aren’t supposed to be anyway.  Some humans do find any way to speed their journey to the ocean and some tunnel through stone and around wood.  Some speed into the ocean with ferocity and strength still pumping and some trickle in after using up their strength.  In that way, humans are like rivers.

I don’t think we were supposed to be though.  I don’t think we were made like that.  We made ourselves like that by evolving through struggles and hardships.  We developed a will to live that forces us to continue beating against that rock in front of us until it bleeds our blood.  But we evolved that way.  That’s not to say the first humans didn’t know how to work through hardship, but they didn’t perform the complex and ridiculous maneuvers we now go through every day in our attempt to survive.  If it was cold, they froze.  If we are cold, we turn up the heater.  

About a year ago, I started my therapy journey.  That is to say, Skoddie finally convinced me I needed a therapist, I made an appointment with one, and attended our first meeting.  I know this was a year ago thanks to Facebook’s “On This Day” feature.  

I meet with that therapist four times before figuring out she wasn’t the right one for me.  She seemed to get it during our first meeting.  We talked about the life changes having gastroparesis had caused, we talked about the desires I could no longer fulfill, and we talked about grief.  That first meeting, she told me my life had permanently changed, and I needed to grieve for the old one before I could accept my new one.

The next few meetings didn’t go as well, and after deciding she wasn’t right for me, I filed that advice away with the rest of her new age spirit healing nonsense, and went in search of a therapist who would be more logical and medical in their approach to my depression and anxiety.  Both seemed to be caused or triggered by the onset of gastroparesis symptoms, and so the approach to treat them as such felt like the right one to me.  When I thought about why I was depressed about life, the answer seemed obvious.  I have gastroparesis, I will probably have it for the rest of my life, and that life is very likely to be shorter than average.

What’s not to be depressed about?

Once again, I never stopped.  I was like a river presented with a rock.  I dug a channel and went around.  It took some time, but the fruits of my labor were a therapist who seems to understand what is going on and how to fix it.  Logically, my river self would continue on its merry way, back on track.  Instead, these last few weeks, I’ve stumbled and stopped, rumbling like there’s a rock in my path but I didn’t know where it was or how to get around it.  I felt like I broke through a week ago when I decided to keep living as long as I could, but that’s really just me deciding to be a river again.  To keep boring through rocks.  

It doesn’t mean I can.

And tonight that quote came back to me.  It felt like the world should have stopped.  Something terrible has happened.  It feels like the world should have stopped and witnessed it.  But it didn’t.  There’s only me, and even I didn’t witness it properly.  I was too busy being a river, when I needed to be a human.

In June of 2013, at the end of that year’s Spring semester of college, during finals no less, I woke up nauseous and threw up until it felt like my stomach was trying to turn itself inside out.  I was 21.  Luckily, I only had dance class that day, and our professor (who would later find out she was pregnant) canceled class due to an unexplained bought of flu (morning sickness).  So I stayed home, didn’t eat anything due to the residing nausea, and woke up the next morning nauseous again.

That first day was a Monday.  I know that because I had a standing babysitting obligation Sundays, and I made a habit of having a glass of wine with my mom after coming home from that, before I went to bed.  So waking up nauseous the next day, I didn’t think I had drunk enough to make me sick, but I attributed it to a hangover or bad wine.  However, I woke up again on Tuesday nauseous.  Maybe hangovers last for two days for other people, but they didn’t for me and I had only had a single glass of wine.  And then it happened again the next day, and the next.  After a week of being unable to keep down solid food, I saw a doctor who accused me of anorexia and kicked me out of her office.  And the rest of the story is, as they say, history.

But that day, that Monday in early June in 2013 when I was 21 years old, was the day the world should have stopped and turned to witness a tragedy.  But no one knew what it was until much later.  Now I am 26, looking back on that day and my confusion, and I can understand why the world doesn’t stop for all tragedies.  It’s because they don’t always look like one.

And that day wasn’t a tragedy for the rest of the world anyway.  It was the first day of my professor’s morning sickness, remember?  It was her first sign of pregnancy.  Can you imagine how she felt the day she found out her flu was an infant?  I wonder if she saw a doctor the same day I did.  I wonder if she was receiving amazing news while I was being escorted out of an urgent care center for lying to the doctors.  But the world didn’t stop for her either.  It treated her miracle the same way it treated my tragedy.  Human life was like a river, and it kept moving.

That’s a weird thought that’s just occurred to me.  I’ve met her daughter three times.  She will never know a world in which I didn’t have an incurable illness, but she doesn’t know that and probably never will.  It has no effect on her life whatsoever.

So how selfish is it really to ask the world to stop for my tragedy?  I didn’t even stop for it.  I kept going, performed a dance final the next week, and threw up after.  The river moves on.  It’s 5 years later and now I’m trying to dig my way around or through the rock of depression.  I have a kindly old therapist who keeps picking up shovels and picks and doing his best to help.

But I never stopped.  I never witnessed.  Even two years after that Monday when a doctor finally told me the name of the thing that was wrong with me.  It was early August and I had known I was going to be moving to Berkeley in a few weeks to go to school.  The world didn’t stop, I didn’t stop.

But it still feels like it should have.  I should have.  My heart is still bleeding for that other life I was going to live.  Maybe my river has formed a loop instead of trying to get around the rock.  Maybe it keeps flowing back to rejoin at that Monday, the waters whisper what if what if what if.

My first therapist told me I needed to grieve, and I did.  I did it so well, I got stuck grieving.  I grieved so hard I turned my river uphill and revisited the past over and over again.  Now I’m back at the rock at the bottom of the loop and there’s my therapist with his shovel trying to dig a channel for me.

I don’t know what I’m saying with this post.  I really don’t.  I guess I’m wondering if I still know how to flow towards the ocean.  I decided I was going to try but can that decision stop the cycling?  

I want it to, but I have to squash the little voice in the back of my head that still wants the world to stop for me.  It still wants recognition that a bad thing has happened.

Because yes, a tragedy befell me in 2013.  And maybe with this post, I will have witnessed it well enough to be a river again.
